//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using System.Data;

using Ares.Cimes.IntelliService;
using Ares.Cimes.IntelliService.DbTableRow;

namespace Ares.Cimes.IntelliService.DbTableSchema
{
  /// <summary>
  /// CST_USR_WORKTIME_HIST table schema 人員上下工HIST資料
  /// </summary>
  public class CST_USR_WORKTIME_HIST : DBTableSchemaBase
  {
    /// <summary>
    /// 該類別的唯一實體, 供 Runtime 才能決定類別情況下使用
    /// </summary>
    public static CST_USR_WORKTIME_HIST Singleton = new CST_USR_WORKTIME_HIST();

    private static int s_NewRowCount = 0;

    #region Properties
    /// <summary>
    /// 此類別對應的資料表名稱。
    /// </summary>
    public static new string TableName { get { return Singleton.m_DataTable.TableName; } }

    /// <summary>
    /// 人員上下工歷史紀錄系統編號 資料型態:NVARCHAR2(100) 是否允許Null:N 
    /// </summary>
    public static DataColumn USR_WORKTIME_HIST_SID { get { return Singleton.Columns["USR_WORKTIME_HIST_SID"]; } } 
    /// <summary>
    /// 人員上下工系統編號 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public static DataColumn USR_WORKTIME_SID { get { return Singleton.Columns["USR_WORKTIME_SID"]; } } 
    /// <summary>
    /// 工單 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public static DataColumn WO { get { return Singleton.Columns["WO"]; } } 
    /// <summary>
    /// 線別/機台 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public static DataColumn LINE { get { return Singleton.Columns["LINE"]; } } 
    /// <summary>
    /// 上工人員 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public static DataColumn WORKUSERID { get { return Singleton.Columns["WORKUSERID"]; } } 
    /// <summary>
    /// 工位 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public static DataColumn USR_WORKPALCE { get { return Singleton.Columns["USR_WORKPALCE"]; } } 
    /// <summary>
    /// 上工時間 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public static DataColumn STARTTIME { get { return Singleton.Columns["STARTTIME"]; } } 
    /// <summary>
    /// 下工時間 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public static DataColumn ENDTIME { get { return Singleton.Columns["ENDTIME"]; } } 
    /// <summary>
    /// 更新人員 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public static DataColumn USERID { get { return Singleton.Columns["USERID"]; } } 
    /// <summary>
    /// 更新時間 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public static DataColumn UPDATETIME { get { return Singleton.Columns["UPDATETIME"]; } } 
    /// <summary>
    /// Comm系统编号 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public static DataColumn COMM_SID { get { return Singleton.Columns["COMM_SID"]; } } 
    /// <summary>
    /// 執行標記 資料型態:CHAR(1) 是否允許Null:Y 
    /// </summary>
    public static DataColumn EXECUTEFLAG { get { return Singleton.Columns["EXECUTEFLAG"]; } } 
    /// <summary>
    /// 班别日期 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public static DataColumn SHIFTDATE { get { return Singleton.Columns["SHIFTDATE"]; } } 
    /// <summary>
    /// 班別 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public static DataColumn SHIFT { get { return Singleton.Columns["SHIFT"]; } } 
    /// <summary>
    /// 人員除外系統編號 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public static DataColumn USR_EXCEPT_WORKTIME_SID { get { return Singleton.Columns["USR_EXCEPT_WORKTIME_SID"]; } } 
    /// <summary>
    ///  資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public static DataColumn LOT { get { return Singleton.Columns["LOT"]; } } 

    #endregion Properties

    #region Ctor()
    
    private CST_USR_WORKTIME_HIST()
    {
        // 不須鎖定 m_DataTable, 因為在這個時點, 不可能 有其他地方 同時存取 m_DataTable       
        
        base.m_DataTable.TableName = "CST_USR_WORKTIME_HIST";
        
        base.SyncColumnsFromDB();
        // #TableColAddStatements
    }
    
    #endregion Ctor()
    
        /// <summary>
        /// 產生一個新的 Row 類別, 以便後續操作如填值等
        /// </summary>
        /// <returns>新的 Row 類別</returns>
        public static CST_USR_WORKTIME_HIST_Row NewRow() { return (CST_USR_WORKTIME_HIST_Row)Singleton.CreateRow(); }

        /// <summary>
        /// 產生一個新的 Row Array, 以便後續操作如填值等
        /// </summary>
        /// <param name="length"></param>
        /// <returns></returns>
        public override DBTableRowBase[] CreateRowArray(int length)
        {
            CST_USR_WORKTIME_HIST_Row[] rowArray = new CST_USR_WORKTIME_HIST_Row[length];
            for (int i = 0; i < rowArray.Length; ++i)
            {
                rowArray[i] = (CST_USR_WORKTIME_HIST_Row)CreateRow();
            }
            return rowArray;
        }
        
        /// <summary>
        /// 無條件取得指定欄位的資料並轉成一個指定型別的陣列
        /// </summary>
        /// <param name="col">指定欄位</param>
        /// <returns>Array</returns>
        public static T[] SelectArray<T>(DataColumn col) { return Singleton.GetArray<T>(col, null, null); }
             
       
        /// <summary>
        /// 產生一個新的 Row 類別, 以便後續操作如填值等
        /// </summary>
        /// <returns></returns>
        public override DBTableRowBase CreateRow() 
        {
            DataRow row = NewRow(ref s_NewRowCount);

            return new CST_USR_WORKTIME_HIST_Row(row);
        }
                
        /// <summary>
        /// 執行傳入的 Sql, 取得符合的第一筆 Record.
        /// </summary>
        /// <param name="sqlAgent">Sql</param>
        /// <returns>Match Row</returns>
        public override DBTableRowBase GetOneRow(SqlAgent sqlAgent)
        {
            return this.GetOneRow<CST_USR_WORKTIME_HIST_Row>(sqlAgent);
        }
      
        #region SelectRows()
       
        /// <summary>
        /// 取得所有欄位，沒有 Where 條件限制，無排序的資料；如果沒有資料則會回傳 Length 為 0 的 Array
        /// </summary>
        /// <returns>Row Array</returns>
        public static CST_USR_WORKTIME_HIST_Row[] SelectRows()
        {
            return Singleton.GetRows<CST_USR_WORKTIME_HIST_Row>(SelectStar.Singleton, null, null);
        }
  
        /// <summary>
        /// 根據 Where 條件, OrderBy 設定取得特定欄位的資料，回傳 XXX_Row[]，
        /// 如果沒有資料則會回傳 Length 為 0 的 Array。
        /// </summary>
        /// <param name="cols">指定欄位s</param>
        /// <returns>Row Array</returns>
        public static CST_USR_WORKTIME_HIST_Row[] SelectRows(DataColumn[] cols)
        {
            return Singleton.GetRows<CST_USR_WORKTIME_HIST_Row>(cols, null, null);
        }
      
        /// <summary>
        /// 根據 SQL 取得指定欄位的資料，回傳 XXX_Row[]，
        /// 如果沒有資料則會回傳 Length 為 0 的 Array。
        /// </summary>
        /// <param name="sql">sql</param>
        /// <returns>Row Array</returns>
        public static CST_USR_WORKTIME_HIST_Row[] SelectRows(SqlAgent sql) { return Singleton.GetRows<CST_USR_WORKTIME_HIST_Row>(sql, "", null); }
              
        /// <summary>
        /// 根據 SQL 取得指定欄位的資料，回傳 XXX_Row[]，
        /// 如果沒有資料則會回傳 Length 為 0 的 Array。
        /// </summary>
        /// <param name="sql">sql</param>
        /// <param name="rowFilter">RowFilter</param>
        /// <returns>Row Array</returns>
        public static CST_USR_WORKTIME_HIST_Row[] SelectRows(SqlAgent sql, string rowFilter) { return Singleton.GetRows<CST_USR_WORKTIME_HIST_Row>(sql, rowFilter, null); }
       
        /// <summary>
        /// 根據 SQL 取得指定欄位的資料，回傳 XXX_Row[]，
        /// 如果沒有資料則會回傳 Length 為 0 的 Array。
        /// </summary>
        /// <param name="sql">sql</param>
        /// <param name="dataAgent">協助查詢的物件</param>
        /// <returns>Row Array</returns>
        public static CST_USR_WORKTIME_HIST_Row[] SelectRows(SqlAgent sql, CustomDataAgent dataAgent) { return Singleton.GetRows<CST_USR_WORKTIME_HIST_Row>(sql, "", dataAgent); }
            
        /// <summary>
        /// 根據 SQL 取得指定欄位的資料，回傳 XXX_Row[]，
        /// 如果沒有資料則會回傳 Length 為 0 的 Array。
        /// </summary>
        /// <param name="sql">sql</param>
        /// <param name="rowFilter">RowFilter</param>
        /// <param name="dataAgent">協助查詢的物件</param>
        /// <returns>Row Array</returns>
        public static CST_USR_WORKTIME_HIST_Row[] SelectRows(SqlAgent sql, string rowFilter, CustomDataAgent dataAgent) { return Singleton.GetRows<CST_USR_WORKTIME_HIST_Row>(sql, rowFilter, dataAgent); }

        #endregion SelectRows()
           

    }  // end class
}  // end namespace
