//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;


using Ares.Cimes.IntelliService.DbTableRow;
using Ares.Cimes.IntelliService.DbTableSchema;

namespace Ares.Cimes.IntelliService.Info
{
    /// <summary>
    ///  (Mapping CST_API_MOLD_RESET_LOG Table)
    /// </summary>
    [Serializable]
    public partial class CSTAPIMoldResetLogInfo : InfoBase 
    {
        private static readonly CSTAPIMoldResetLogInfo s_ProxyInfo;
        
        
        
        private CST_API_MOLD_RESET_LOG_Row m_StrongTypeRow { get { return (CST_API_MOLD_RESET_LOG_Row)GetSchemaRow(); } }

        /// <summary>
        /// Non-Static Proxy Info Get Property
        /// </summary>        
        protected override InfoBase ProxyInfo { get { return s_ProxyInfo; } }

        #region Properties
        /// <summary>
        /// #SIDColumnName
        /// </summary>
        protected override DataColumn IDColumn { get { return CST_API_MOLD_RESET_LOG.API_MOLD_RESET_LOG_SID; } }
        
                /// <summary>
        /// SID 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String ApiMoldResetLogSID 
        {
            get { return m_StrongTypeRow.API_MOLD_RESET_LOG_SID; }
            set { m_StrongTypeRow.API_MOLD_RESET_LOG_SID = value; }
        }
        /// <summary>
        /// 模具 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String MoldName 
        {
            get { return m_StrongTypeRow.MOLD_NAME; }
            set { m_StrongTypeRow.MOLD_NAME = value; }
        }
        /// <summary>
        /// Reset前的最終次數 資料型態:NUMBER() 是否允許Null:Y 
        /// </summary>
        public Decimal FinalCount 
        {
            get { return m_StrongTypeRow.FINAL_COUNT; }
            set { m_StrongTypeRow.FINAL_COUNT = value; }
        }
        /// <summary>
        /// RESET時間 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String ResetTime 
        {
            get { return m_StrongTypeRow.RESETTIME; }
            set { m_StrongTypeRow.RESETTIME = value; }
        }

                
        /// <summary>
        /// User ID
        /// </summary>
        public override string UserID { get { return m_StrongTypeRow.USERID; } protected set { m_StrongTypeRow.USERID = value; } }
        
        /// <summary>
        /// Update Time
        /// </summary>
        public override string UpdateTime { get { return m_StrongTypeRow.UPDATETIME; } protected set { m_StrongTypeRow.UPDATETIME = value; } }
        #endregion Properties

        #region Ctor(...)
        static CSTAPIMoldResetLogInfo()
        {
            CSTAPIMoldResetLogInfo info = new CSTAPIMoldResetLogInfo();
            info.SetSchemaRow(CST_API_MOLD_RESET_LOG.NewRow());
            s_ProxyInfo = info;
        }
        
        /// <summary>
        /// 建構一空的 CSTAPIMoldResetLogInfo 物件, 此 Ctor 是供 Generator 使用, 請勿直接呼叫.
        /// </summary>
        public CSTAPIMoldResetLogInfo() { }
        
        /// <summary>
        /// 建構一新的 CSTAPIMoldResetLogInfo object，由指定的 CST_API_MOLD_RESET_LOG_Row 為 Raw Row。
        /// 此 Ctor 只供內部程式呼叫使用, 不為 public ctor.
        /// </summary>
        [Obsolete("已被 InfoBase.Create method 取代")]
        protected internal CSTAPIMoldResetLogInfo(CST_API_MOLD_RESET_LOG_Row row) : base(row) { }
        #endregion
        
     
		
    }
}

