//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;


using Ares.Cimes.IntelliService.DbTableRow;
using Ares.Cimes.IntelliService.DbTableSchema;

namespace Ares.Cimes.IntelliService.Info
{
    /// <summary>
    ///  (Mapping CST_API_EAP_SERVER Table)
    /// </summary>
    [Serializable]
    public partial class CSTAPIEAPServerInfo : InfoBase 
    {
        private static readonly CSTAPIEAPServerInfo s_ProxyInfo;
        
        
        
        private CST_API_EAP_SERVER_Row m_StrongTypeRow { get { return (CST_API_EAP_SERVER_Row)GetSchemaRow(); } }

        /// <summary>
        /// Non-Static Proxy Info Get Property
        /// </summary>        
        protected override InfoBase ProxyInfo { get { return s_ProxyInfo; } }

        #region Properties
        /// <summary>
        /// EAP_NAME
        /// </summary>
        protected override DataColumn IDColumn { get { return CST_API_EAP_SERVER.API_EAP_SERVER; } }
        
                /// <summary>
        /// EAP設定系統編號 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String APIEAPServer 
        {
            get { return m_StrongTypeRow.API_EAP_SERVER; }
            set { m_StrongTypeRow.API_EAP_SERVER = value; }
        }
        /// <summary>
        /// EAP SERVER名稱 資料型態:NVARCHAR2(100) 是否允許Null:N 
        /// </summary>
        public String EAPName 
        {
            get { return m_StrongTypeRow.EAP_NAME; }
            set { m_StrongTypeRow.EAP_NAME = value; }
        }
        /// <summary>
        /// EAP SERVER的IP 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String IP 
        {
            get { return m_StrongTypeRow.IP; }
            set { m_StrongTypeRow.IP = value; }
        }
        /// <summary>
        /// EAP SERVER的Port 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String Port 
        {
            get { return m_StrongTypeRow.PORT; }
            set { m_StrongTypeRow.PORT = value; }
        }

        /// <summary>
        /// EAP SERVER的Line 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String Line
        {
            get { return m_StrongTypeRow.LINE; }
            set { m_StrongTypeRow.LINE = value; }
        }


        ///// <summary>
        ///// User ID
        ///// </summary>
        //public override string UserID { get { return m_StrongTypeRow.USERID; } protected set { m_StrongTypeRow.USERID = value; } }

        ///// <summary>
        ///// Update Time
        ///// </summary>
        //public override string UpdateTime { get { return m_StrongTypeRow.UPDATETIME; } protected set { m_StrongTypeRow.UPDATETIME = value; } }
        #endregion Properties

        #region Ctor(...)
        static CSTAPIEAPServerInfo()
        {
            CSTAPIEAPServerInfo info = new CSTAPIEAPServerInfo();
            info.SetSchemaRow(CST_API_EAP_SERVER.NewRow());
            s_ProxyInfo = info;
        }
        
        /// <summary>
        /// 建構一空的 CSTAPIEAPServerInfo 物件, 此 Ctor 是供 Generator 使用, 請勿直接呼叫.
        /// </summary>
        public CSTAPIEAPServerInfo() { }
        
        /// <summary>
        /// 建構一新的 CSTAPIEAPServerInfo object，由指定的 CST_API_EAP_SERVER_Row 為 Raw Row。
        /// 此 Ctor 只供內部程式呼叫使用, 不為 public ctor.
        /// </summary>
        [Obsolete("已被 InfoBase.Create method 取代")]
        protected internal CSTAPIEAPServerInfo(CST_API_EAP_SERVER_Row row) : base(row) { }
        #endregion
        
     
		
    }
}

