//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;


using Ares.Cimes.IntelliService.DbTableRow;
using Ares.Cimes.IntelliService.DbTableSchema;

namespace Ares.Cimes.IntelliService.Info
{
    /// <summary>
    /// 清洗機參數收集表 (Mapping CST_API_CLEANING_DATA Table)
    /// </summary>
    [Serializable]
    public partial class CSTAPICleaningDataInfo : InfoBase 
    {
        private static readonly CSTAPICleaningDataInfo s_ProxyInfo;
        
        
        
        private CST_API_CLEANING_DATA_Row m_StrongTypeRow { get { return (CST_API_CLEANING_DATA_Row)GetSchemaRow(); } }

        /// <summary>
        /// Non-Static Proxy Info Get Property
        /// </summary>        
        protected override InfoBase ProxyInfo { get { return s_ProxyInfo; } }

        #region Properties
        /// <summary>
        /// #SIDColumnName
        /// </summary>
        protected override DataColumn IDColumn { get { return CST_API_CLEANING_DATA.API_CLEANING_DATA_SID; } }
        
                /// <summary>
        /// SID 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String APICleaningDataSID 
        {
            get { return m_StrongTypeRow.API_CLEANING_DATA_SID; }
            set { m_StrongTypeRow.API_CLEANING_DATA_SID = value; }
        }
        /// <summary>
        /// 位置 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String Location 
        {
            get { return m_StrongTypeRow.LOCATION; }
            set { m_StrongTypeRow.LOCATION = value; }
        }
        /// <summary>
        /// 脫脂濃度 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String DegreasingConcentration 
        {
            get { return m_StrongTypeRow.DEGREASING_CONCENTRATION; }
            set { m_StrongTypeRow.DEGREASING_CONCENTRATION = value; }
        }
        /// <summary>
        /// 脫脂水溫 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String DegreasingTemp 
        {
            get { return m_StrongTypeRow.DEGREASING_TEMP; }
            set { m_StrongTypeRow.DEGREASING_TEMP = value; }
        }
        /// <summary>
        /// 清水水溫 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String WaterTemp 
        {
            get { return m_StrongTypeRow.WATER_TEMP; }
            set { m_StrongTypeRow.WATER_TEMP = value; }
        }
        /// <summary>
        /// 烘乾溫度 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String DryingTemp 
        {
            get { return m_StrongTypeRow.DRYING_TEMP; }
            set { m_StrongTypeRow.DRYING_TEMP = value; }
        }
        /// <summary>
        /// 出口溫度 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String ExitTemp 
        {
            get { return m_StrongTypeRow.EXIT_TEMP; }
            set { m_StrongTypeRow.EXIT_TEMP = value; }
        }

                
        /// <summary>
        /// User ID
        /// </summary>
        public override string UserID { get { return m_StrongTypeRow.USERID; } protected set { m_StrongTypeRow.USERID = value; } }
        
        /// <summary>
        /// Update Time
        /// </summary>
        public override string UpdateTime { get { return m_StrongTypeRow.UPDATETIME; } protected set { m_StrongTypeRow.UPDATETIME = value; } }
        #endregion Properties

        #region Ctor(...)
        static CSTAPICleaningDataInfo()
        {
            CSTAPICleaningDataInfo info = new CSTAPICleaningDataInfo();
            info.SetSchemaRow(CST_API_CLEANING_DATA.NewRow());
            s_ProxyInfo = info;
        }
        
        /// <summary>
        /// 建構一空的 CSTAPICleaningDataInfo 物件, 此 Ctor 是供 Generator 使用, 請勿直接呼叫.
        /// </summary>
        public CSTAPICleaningDataInfo() { }
        
        /// <summary>
        /// 建構一新的 CSTAPICleaningDataInfo object，由指定的 CST_API_CLEANING_DATA_Row 為 Raw Row。
        /// 此 Ctor 只供內部程式呼叫使用, 不為 public ctor.
        /// </summary>
        [Obsolete("已被 InfoBase.Create method 取代")]
        protected internal CSTAPICleaningDataInfo(CST_API_CLEANING_DATA_Row row) : base(row) { }
        #endregion
        
     
		
    }
}

