//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;


using Ares.Cimes.IntelliService.DbTableRow;
using Ares.Cimes.IntelliService.DbTableSchema;

namespace Ares.Cimes.IntelliService.Info
{
    /// <summary>
    ///  (Mapping CST_API_MOLD_COUNT Table)
    /// </summary>
    [Serializable]
    public partial class CSTAPIMoldCountInfo : InfoBase 
    {
        private static readonly CSTAPIMoldCountInfo s_ProxyInfo;
        
        
        
        private CST_API_MOLD_COUNT_Row m_StrongTypeRow { get { return (CST_API_MOLD_COUNT_Row)GetSchemaRow(); } }

        /// <summary>
        /// Non-Static Proxy Info Get Property
        /// </summary>        
        protected override InfoBase ProxyInfo { get { return s_ProxyInfo; } }

        #region Properties
        /// <summary>
        /// API_MOLD_COUNT_SID
        /// </summary>
        protected override DataColumn IDColumn { get { return CST_API_MOLD_COUNT.API_MOLD_COUNT_SID; } }
        
                /// <summary>
        /// SID 資料型態:NVARCHAR2(100) 是否允許Null:N 
        /// </summary>
        public String ApiMoldCountSID 
        {
            get { return m_StrongTypeRow.API_MOLD_COUNT_SID; }
            set { m_StrongTypeRow.API_MOLD_COUNT_SID = value; }
        }
        /// <summary>
        /// 模具 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String MoldName 
        {
            get { return m_StrongTypeRow.MOLD_NAME; }
            set { m_StrongTypeRow.MOLD_NAME = value; }
        }
        /// <summary>
        /// 模具次數 資料型態:NUMBER() 是否允許Null:Y 
        /// </summary>
        public Decimal MoldCount 
        {
            get { return m_StrongTypeRow.MOLD_COUNT; }
            set { m_StrongTypeRow.MOLD_COUNT = value; }
        }

                
        /// <summary>
        /// User ID
        /// </summary>
        public override string UserID { get { return m_StrongTypeRow.USERID; } protected set { m_StrongTypeRow.USERID = value; } }
        
        /// <summary>
        /// Update Time
        /// </summary>
        public override string UpdateTime { get { return m_StrongTypeRow.UPDATETIME; } protected set { m_StrongTypeRow.UPDATETIME = value; } }
        #endregion Properties

        #region Ctor(...)
        static CSTAPIMoldCountInfo()
        {
            CSTAPIMoldCountInfo info = new CSTAPIMoldCountInfo();
            info.SetSchemaRow(CST_API_MOLD_COUNT.NewRow());
            s_ProxyInfo = info;
        }
        
        /// <summary>
        /// 建構一空的 CSTAPIMoldCountInfo 物件, 此 Ctor 是供 Generator 使用, 請勿直接呼叫.
        /// </summary>
        public CSTAPIMoldCountInfo() { }
        
        /// <summary>
        /// 建構一新的 CSTAPIMoldCountInfo object，由指定的 CST_API_MOLD_COUNT_Row 為 Raw Row。
        /// 此 Ctor 只供內部程式呼叫使用, 不為 public ctor.
        /// </summary>
        [Obsolete("已被 InfoBase.Create method 取代")]
        protected internal CSTAPIMoldCountInfo(CST_API_MOLD_COUNT_Row row) : base(row) { }
        #endregion
        
     
		
    }
}

