//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;


using Ares.Cimes.IntelliService.DbTableRow;
using Ares.Cimes.IntelliService.DbTableSchema;

namespace Ares.Cimes.IntelliService.Info
{
    /// <summary>
    ///  (Mapping CST_CMS_CAR_PROCESS Table)
    /// </summary>
    [Serializable]
    public partial class CSTCMSCarProcessInfo : InfoBase 
    {
        private static readonly CSTCMSCarProcessInfo s_ProxyInfo;
        
        
        
        private CST_CMS_CAR_PROCESS_Row m_StrongTypeRow { get { return (CST_CMS_CAR_PROCESS_Row)GetSchemaRow(); } }

        /// <summary>
        /// Non-Static Proxy Info Get Property
        /// </summary>        
        protected override InfoBase ProxyInfo { get { return s_ProxyInfo; } }

        #region Properties
        /// <summary>
        /// #SIDColumnName
        /// </summary>
        protected override DataColumn IDColumn { get { return CST_CMS_CAR_PROCESS.CMS_CAR_PROCESS_SID; } }
        
                /// <summary>
        ///  資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String CMSCarProcessSID 
        {
            get { return m_StrongTypeRow.CMS_CAR_PROCESS_SID; }
            set { m_StrongTypeRow.CMS_CAR_PROCESS_SID = value; }
        }
        /// <summary>
        ///  資料型態:NVARCHAR2(5) 是否允許Null:Y 
        /// </summary>
        public String CarSequence 
        {
            get { return m_StrongTypeRow.CAR_SEQ; }
            set { m_StrongTypeRow.CAR_SEQ = value; }
        }
        /// <summary>
        ///  資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String CarNo 
        {
            get { return m_StrongTypeRow.CAR_NO; }
            set { m_StrongTypeRow.CAR_NO = value; }
        }
        /// <summary>
        ///  資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String Line
        {
            get { return m_StrongTypeRow.LINE; }
            set { m_StrongTypeRow.LINE = value; }
        }
        /// <summary>
        ///  資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String GroupSID
        {
            get { return m_StrongTypeRow.GROUP_SID; }
            set { m_StrongTypeRow.GROUP_SID = value; }
        }
        /// <summary>
        ///  資料型態:NVARCHAR2(5) 是否允許Null:Y 
        /// </summary>
        public String LoadLotFlag 
        {
            get { return m_StrongTypeRow.LOADLOT_FLAG; }
            set { m_StrongTypeRow.LOADLOT_FLAG = value; }
        }

                
        /// <summary>
        /// User ID
        /// </summary>
        public override string UserID { get { return m_StrongTypeRow.USERID; } protected set { m_StrongTypeRow.USERID = value; } }
        
        /// <summary>
        /// Update Time
        /// </summary>
        public override string UpdateTime { get { return m_StrongTypeRow.UPDATETIME; } protected set { m_StrongTypeRow.UPDATETIME = value; } }
        #endregion Properties

        #region Ctor(...)
        static CSTCMSCarProcessInfo()
        {
            CSTCMSCarProcessInfo info = new CSTCMSCarProcessInfo();
            info.SetSchemaRow(CST_CMS_CAR_PROCESS.NewRow());
            s_ProxyInfo = info;
        }
        
        /// <summary>
        /// 建構一空的 CSTCMSCarProcessInfo 物件, 此 Ctor 是供 Generator 使用, 請勿直接呼叫.
        /// </summary>
        public CSTCMSCarProcessInfo() { }
        
        /// <summary>
        /// 建構一新的 CSTCMSCarProcessInfo object，由指定的 CST_CMS_CAR_PROCESS_Row 為 Raw Row。
        /// 此 Ctor 只供內部程式呼叫使用, 不為 public ctor.
        /// </summary>
        [Obsolete("已被 InfoBase.Create method 取代")]
        protected internal CSTCMSCarProcessInfo(CST_CMS_CAR_PROCESS_Row row) : base(row) { }
        #endregion
        
     
		
    }
}

