//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;


using Ares.Cimes.IntelliService.DbTableRow;
using Ares.Cimes.IntelliService.DbTableSchema;

namespace Ares.Cimes.IntelliService.Info
{
    /// <summary>
    /// 收集載具通過T4T6溫度時間的編號 (Mapping CST_CMS_TEMP_TIME_LOG Table)
    /// </summary>
    [Serializable]
    public partial class CSTCMSTempTimeLogInfo : InfoBase 
    {
        private static readonly CSTCMSTempTimeLogInfo s_ProxyInfo;
        
        
        
        private CST_CMS_TEMP_TIME_LOG_Row m_StrongTypeRow { get { return (CST_CMS_TEMP_TIME_LOG_Row)GetSchemaRow(); } }

        /// <summary>
        /// Non-Static Proxy Info Get Property
        /// </summary>        
        protected override InfoBase ProxyInfo { get { return s_ProxyInfo; } }

        #region Properties
        /// <summary>
        /// #SIDColumnName
        /// </summary>
        protected override DataColumn IDColumn { get { return CST_CMS_TEMP_TIME_LOG.CMS_TEMP_TIME_LOG_SID; } }
        
                /// <summary>
        /// 收集載具通過T4T6溫度時間的LOG編號 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String CMSTempTimeLogSID 
        {
            get { return m_StrongTypeRow.CMS_TEMP_TIME_LOG_SID; }
            set { m_StrongTypeRow.CMS_TEMP_TIME_LOG_SID = value; }
        }
        /// <summary>
        /// 收集載具通過T4T6溫度時間的編號 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String CMSTempTimeSID 
        {
            get { return m_StrongTypeRow.CMS_TEMP_TIME_SID; }
            set { m_StrongTypeRow.CMS_TEMP_TIME_SID = value; }
        }
        /// <summary>
        /// 載具批號系統編號 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String CMSLotSID 
        {
            get { return m_StrongTypeRow.CMS_LOT_SID; }
            set { m_StrongTypeRow.CMS_LOT_SID = value; }
        }
        /// <summary>
        /// 倒數第1隻的溫度 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String TEMP1 
        {
            get { return m_StrongTypeRow.TEMP1; }
            set { m_StrongTypeRow.TEMP1 = value; }
        }
        /// <summary>
        /// 倒數第2隻的溫度 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String TEMP2 
        {
            get { return m_StrongTypeRow.TEMP2; }
            set { m_StrongTypeRow.TEMP2 = value; }
        }
        /// <summary>
        /// 水溫 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String TempWater 
        {
            get { return m_StrongTypeRow.TEMP_WATER; }
            set { m_StrongTypeRow.TEMP_WATER = value; }
        }
        /// <summary>
        /// 高熱爐開門到下水時間 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String TransportTime 
        {
            get { return m_StrongTypeRow.TRANSPORT_TIME; }
            set { m_StrongTypeRow.TRANSPORT_TIME = value; }
        }
        /// <summary>
        /// 浸水時間 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String InWaterTime 
        {
            get { return m_StrongTypeRow.IN_WATER_TIME; }
            set { m_StrongTypeRow.IN_WATER_TIME = value; }
        }

                
        /// <summary>
        /// User ID
        /// </summary>
        public override string UserID { get { return m_StrongTypeRow.USERID; } protected set { m_StrongTypeRow.USERID = value; } }
        
        /// <summary>
        /// Update Time
        /// </summary>
        public override string UpdateTime { get { return m_StrongTypeRow.UPDATETIME; } protected set { m_StrongTypeRow.UPDATETIME = value; } }
        #endregion Properties

        #region Ctor(...)
        static CSTCMSTempTimeLogInfo()
        {
            CSTCMSTempTimeLogInfo info = new CSTCMSTempTimeLogInfo();
            info.SetSchemaRow(CST_CMS_TEMP_TIME_LOG.NewRow());
            s_ProxyInfo = info;
        }
        
        /// <summary>
        /// 建構一空的 CSTCMSTempTimeLogInfo 物件, 此 Ctor 是供 Generator 使用, 請勿直接呼叫.
        /// </summary>
        public CSTCMSTempTimeLogInfo() { }
        
        /// <summary>
        /// 建構一新的 CSTCMSTempTimeLogInfo object，由指定的 CST_CMS_TEMP_TIME_LOG_Row 為 Raw Row。
        /// 此 Ctor 只供內部程式呼叫使用, 不為 public ctor.
        /// </summary>
        [Obsolete("已被 InfoBase.Create method 取代")]
        protected internal CSTCMSTempTimeLogInfo(CST_CMS_TEMP_TIME_LOG_Row row) : base(row) { }
        #endregion
        
     
		
    }
}

