//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;


using Ares.Cimes.IntelliService.DbTableRow;
using Ares.Cimes.IntelliService.DbTableSchema;

namespace Ares.Cimes.IntelliService.Info
{
    /// <summary>
    ///  (Mapping CST_EDC_COMP Table)
    /// </summary>
    [Serializable]
    public partial class CSTEDCComponentInfo : InfoBase 
    {
        private static readonly CSTEDCComponentInfo s_ProxyInfo;
        
        
        
        private CST_EDC_COMP_Row m_StrongTypeRow { get { return (CST_EDC_COMP_Row)GetSchemaRow(); } }

        /// <summary>
        /// Non-Static Proxy Info Get Property
        /// </summary>        
        protected override InfoBase ProxyInfo { get { return s_ProxyInfo; } }

        #region Properties
        /// <summary>
        /// EDC_COMP_SID
        /// </summary>
        protected override DataColumn IDColumn { get { return CST_EDC_COMP.EDC_COMP_SID; } }
        
                /// <summary>
        ///  資料型態:NVARCHAR2(100) 是否允許Null:N 
        /// </summary>
        public String EDC_COMP_SID 
        {
            get { return m_StrongTypeRow.EDC_COMP_SID; }
            set { m_StrongTypeRow.EDC_COMP_SID = value; }
        }
        /// <summary>
        ///  資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String Lot 
        {
            get { return m_StrongTypeRow.LOT; }
            set { m_StrongTypeRow.LOT = value; }
        }
        /// <summary>
        ///  資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String ComponentID 
        {
            get { return m_StrongTypeRow.COMPONENTID; }
            set { m_StrongTypeRow.COMPONENTID = value; }
        }
        /// <summary>
        ///  資料型態:NUMBER() 是否允許Null:Y 
        /// </summary>
        public Decimal Data 
        {
            get { return m_StrongTypeRow.DATA; }
            set { m_StrongTypeRow.DATA = value; }
        }
        /// <summary>
        ///  資料型態:NUMBER() 是否允許Null:Y 
        /// </summary>
        public Decimal UpSpecification 
        {
            get { return m_StrongTypeRow.UPSPEC; }
            set { m_StrongTypeRow.UPSPEC = value; }
        }
        /// <summary>
        ///  資料型態:NUMBER() 是否允許Null:Y 
        /// </summary>
        public Decimal LowSpecification 
        {
            get { return m_StrongTypeRow.LOWSPEC; }
            set { m_StrongTypeRow.LOWSPEC = value; }
        }
        /// <summary>
        ///  資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String INSPEC 
        {
            get { return m_StrongTypeRow.INSPEC; }
            set { m_StrongTypeRow.INSPEC = value; }
        }

        /// <summary>
        ///  資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String LinkSID
        {
            get { return m_StrongTypeRow.LINKSID; }
            set { m_StrongTypeRow.LINKSID = value; }
        }


        /// <summary>
        /// User ID
        /// </summary>
        public override string UserID { get { return m_StrongTypeRow.USERID; } protected set { m_StrongTypeRow.USERID = value; } }
        
        /// <summary>
        /// Update Time
        /// </summary>
        public override string UpdateTime { get { return m_StrongTypeRow.UPDATETIME; } protected set { m_StrongTypeRow.UPDATETIME = value; } }
        #endregion Properties

        #region Ctor(...)
        static CSTEDCComponentInfo()
        {
            CSTEDCComponentInfo info = new CSTEDCComponentInfo();
            info.SetSchemaRow(CST_EDC_COMP.NewRow());
            s_ProxyInfo = info;
        }
        
        /// <summary>
        /// 建構一空的 CSREDCComponentInfo 物件, 此 Ctor 是供 Generator 使用, 請勿直接呼叫.
        /// </summary>
        public CSTEDCComponentInfo() { }
        
        /// <summary>
        /// 建構一新的 CSREDCComponentInfo object，由指定的 CST_EDC_COMP_Row 為 Raw Row。
        /// 此 Ctor 只供內部程式呼叫使用, 不為 public ctor.
        /// </summary>
        [Obsolete("已被 InfoBase.Create method 取代")]
        protected internal CSTEDCComponentInfo(CST_EDC_COMP_Row row) : base(row) { }
        #endregion
        
     
		
    }
}

