//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;


using Ares.Cimes.IntelliService.DbTableRow;
using Ares.Cimes.IntelliService.DbTableSchema;

namespace Ares.Cimes.IntelliService.Info
{
    /// <summary>
    /// 機台首件資料表 (Mapping CST_EQP_FAI Table)
    /// </summary>
    [Serializable]
    public partial class CSTEquipmentFAIInfo : InfoBase 
    {
        private static readonly CSTEquipmentFAIInfo s_ProxyInfo;
        
        
        
        private CST_EQP_FAI_Row m_StrongTypeRow { get { return (CST_EQP_FAI_Row)GetSchemaRow(); } }

        /// <summary>
        /// Non-Static Proxy Info Get Property
        /// </summary>        
        protected override InfoBase ProxyInfo { get { return s_ProxyInfo; } }

        #region Properties
        /// <summary>
        /// DEVICE
        /// </summary>
        protected override DataColumn IDColumn { get { return CST_EQP_FAI.EQP_FAI_SID; } }
        
                /// <summary>
        /// 機台首件表SID 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String EQP_FAI_SID 
        {
            get { return m_StrongTypeRow.EQP_FAI_SID; }
            set { m_StrongTypeRow.EQP_FAI_SID = value; }
        }
        /// <summary>
        /// 機台調機SID 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String EQP_SETUP_SID 
        {
            get { return m_StrongTypeRow.EQP_SETUP_SID; }
            set { m_StrongTypeRow.EQP_SETUP_SID = value; }
        }
        /// <summary>
        /// 機台 資料型態:NVARCHAR2(100) 是否允許Null:N 
        /// </summary>
        public String EquipmentName 
        {
            get { return m_StrongTypeRow.EQUIPMENT; }
            set { m_StrongTypeRow.EQUIPMENT = value; }
        }
        /// <summary>
        /// 料號 資料型態:NVARCHAR2(100) 是否允許Null:N 
        /// </summary>
        public String DeviceName 
        {
            get { return m_StrongTypeRow.DEVICE; }
            set { m_StrongTypeRow.DEVICE = value; }
        }
        /// <summary>
        /// 檢驗方式：連N(CN), 首N(FN) 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String INSPTYPE 
        {
            get { return m_StrongTypeRow.INSPTYPE; }
            set { m_StrongTypeRow.INSPTYPE = value; }
        }
        /// <summary>
        /// 指定首件次數 資料型態:NUMBER() 是否允許Null:Y 
        /// </summary>
        public Decimal FAICOUNT 
        {
            get { return m_StrongTypeRow.FAICOUNT; }
            set { m_StrongTypeRow.FAICOUNT = value; }
        }
        /// <summary>
        /// 待檢驗次數 資料型態:NUMBER(38) 是否允許Null:Y 
        /// </summary>
        public Decimal WAITFAICOUNT 
        {
            get { return m_StrongTypeRow.WAITFAICOUNT; }
            set { m_StrongTypeRow.WAITFAICOUNT = value; }
        }

                
        /// <summary>
        /// User ID
        /// </summary>
        public override string UserID { get { return m_StrongTypeRow.USERID; } protected set { m_StrongTypeRow.USERID = value; } }
        
        /// <summary>
        /// Update Time
        /// </summary>
        public override string UpdateTime { get { return m_StrongTypeRow.UPDATETIME; } protected set { m_StrongTypeRow.UPDATETIME = value; } }
        #endregion Properties

        #region Ctor(...)
        static CSTEquipmentFAIInfo()
        {
            CSTEquipmentFAIInfo info = new CSTEquipmentFAIInfo();
            info.SetSchemaRow(CST_EQP_FAI.NewRow());
            s_ProxyInfo = info;
        }
        
        /// <summary>
        /// 建構一空的 CSTEquipmentFAIInfo 物件, 此 Ctor 是供 Generator 使用, 請勿直接呼叫.
        /// </summary>
        public CSTEquipmentFAIInfo() { }
        
        /// <summary>
        /// 建構一新的 CSTEquipmentFAIInfo object，由指定的 CST_EQP_FAI_Row 為 Raw Row。
        /// 此 Ctor 只供內部程式呼叫使用, 不為 public ctor.
        /// </summary>
        [Obsolete("已被 InfoBase.Create method 取代")]
        protected internal CSTEquipmentFAIInfo(CST_EQP_FAI_Row row) : base(row) { }
        #endregion
        
     
		
    }
}

