//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;


using Ares.Cimes.IntelliService.DbTableRow;
using Ares.Cimes.IntelliService.DbTableSchema;

namespace Ares.Cimes.IntelliService.Info
{
    /// <summary>
    /// 紀錄機台調機資訊 (Mapping CST_EQP_SETUP Table)
    /// </summary>
    [Serializable]
    public partial class CSTEquipmentSetupInfo : InfoBase 
    {
        private static readonly CSTEquipmentSetupInfo s_ProxyInfo;
        
        
        
        private CST_EQP_SETUP_Row m_StrongTypeRow { get { return (CST_EQP_SETUP_Row)GetSchemaRow(); } }

        /// <summary>
        /// Non-Static Proxy Info Get Property
        /// </summary>        
        protected override InfoBase ProxyInfo { get { return s_ProxyInfo; } }

        #region Properties
        /// <summary>
        /// #SIDColumnName
        /// </summary>
        protected override DataColumn IDColumn { get { return CST_EQP_SETUP.EQP_SETUP_SID; } }
        
                /// <summary>
        /// 機台調機SID 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String EQP_SETUP_SID 
        {
            get { return m_StrongTypeRow.EQP_SETUP_SID; }
            set { m_StrongTypeRow.EQP_SETUP_SID = value; }
        }
        /// <summary>
        /// 機台 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String EquipmentName 
        {
            get { return m_StrongTypeRow.EQUIPMENT; }
            set { m_StrongTypeRow.EQUIPMENT = value; }
        }
        /// <summary>
        /// 調機原因 資料型態:NVARCHAR2(98) 是否允許Null:Y 
        /// </summary>
        public String Reason 
        {
            get { return m_StrongTypeRow.REASON; }
            set { m_StrongTypeRow.REASON = value; }
        }
        /// <summary>
        /// 調機說明 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String Description 
        {
            get { return m_StrongTypeRow.DESCR; }
            set { m_StrongTypeRow.DESCR = value; }
        }
        /// <summary>
        /// 調機開始時間 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String StartTime 
        {
            get { return m_StrongTypeRow.STARTTIME; }
            set { m_StrongTypeRow.STARTTIME = value; }
        }
        /// <summary>
        /// 調機結束時間 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String EndTime 
        {
            get { return m_StrongTypeRow.ENDTIME; }
            set { m_StrongTypeRow.ENDTIME = value; }
        }
        /// <summary>
        /// 調機開始人員 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String STARTUSER 
        {
            get { return m_StrongTypeRow.STARTUSER; }
            set { m_StrongTypeRow.STARTUSER = value; }
        }
        /// <summary>
        /// 調機結束人員 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String ENDUSER 
        {
            get { return m_StrongTypeRow.ENDUSER; }
            set { m_StrongTypeRow.ENDUSER = value; }
        }

                
        /// <summary>
        /// User ID
        /// </summary>
        public override string UserID { get { return m_StrongTypeRow.USERID; } protected set { m_StrongTypeRow.USERID = value; } }
        
        /// <summary>
        /// Update Time
        /// </summary>
        public override string UpdateTime { get { return m_StrongTypeRow.UPDATETIME; } protected set { m_StrongTypeRow.UPDATETIME = value; } }
        #endregion Properties

        #region Ctor(...)
        static CSTEquipmentSetupInfo()
        {
            CSTEquipmentSetupInfo info = new CSTEquipmentSetupInfo();
            info.SetSchemaRow(CST_EQP_SETUP.NewRow());
            s_ProxyInfo = info;
        }
        
        /// <summary>
        /// 建構一空的 CSTEquipmentSetupInfo 物件, 此 Ctor 是供 Generator 使用, 請勿直接呼叫.
        /// </summary>
        public CSTEquipmentSetupInfo() { }
        
        /// <summary>
        /// 建構一新的 CSTEquipmentSetupInfo object，由指定的 CST_EQP_SETUP_Row 為 Raw Row。
        /// 此 Ctor 只供內部程式呼叫使用, 不為 public ctor.
        /// </summary>
        [Obsolete("已被 InfoBase.Create method 取代")]
        protected internal CSTEquipmentSetupInfo(CST_EQP_SETUP_Row row) : base(row) { }
        #endregion
        
     
		
    }
}

