//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;


using Ares.Cimes.IntelliService.DbTableRow;
using Ares.Cimes.IntelliService.DbTableSchema;

namespace Ares.Cimes.IntelliService.Info
{
    /// <summary>
    ///  (Mapping CST_EQP_WO_ASSIGN Table)
    /// </summary>
    [Serializable]
    public partial class CSTEQPWOAssignInfo : InfoBase 
    {
        private static readonly CSTEQPWOAssignInfo s_ProxyInfo;
        
        
        
        private CST_EQP_WO_ASSIGN_Row m_StrongTypeRow { get { return (CST_EQP_WO_ASSIGN_Row)GetSchemaRow(); } }

        /// <summary>
        /// Non-Static Proxy Info Get Property
        /// </summary>        
        protected override InfoBase ProxyInfo { get { return s_ProxyInfo; } }

        #region Properties
        /// <summary>
        /// EQP_WO_ASSIGN_SID
        /// </summary>
        protected override DataColumn IDColumn { get { return CST_EQP_WO_ASSIGN.EQP_WO_ASSIGN_SID; } }
        
                /// <summary>
        /// 系統編號 資料型態:NVARCHAR2(100) 是否允許Null:N 
        /// </summary>
        public String EQP_WO_ASSIGN_SID 
        {
            get { return m_StrongTypeRow.EQP_WO_ASSIGN_SID; }
            set { m_StrongTypeRow.EQP_WO_ASSIGN_SID = value; }
        }
        /// <summary>
        /// 工單編號 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String WorkOrder 
        {
            get { return m_StrongTypeRow.WO; }
            set { m_StrongTypeRow.WO = value; }
        }
        /// <summary>
        /// 機台名稱 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String EquipmentName 
        {
            get { return m_StrongTypeRow.EQP; }
            set { m_StrongTypeRow.EQP = value; }
        }

                
        /// <summary>
        /// User ID
        /// </summary>
        public override string UserID { get { return m_StrongTypeRow.USERID; } protected set { m_StrongTypeRow.USERID = value; } }
        
        /// <summary>
        /// Update Time
        /// </summary>
        public override string UpdateTime { get { return m_StrongTypeRow.UPDATETIME; } protected set { m_StrongTypeRow.UPDATETIME = value; } }
        #endregion Properties

        #region Ctor(...)
        static CSTEQPWOAssignInfo()
        {
            CSTEQPWOAssignInfo info = new CSTEQPWOAssignInfo();
            info.SetSchemaRow(CST_EQP_WO_ASSIGN.NewRow());
            s_ProxyInfo = info;
        }
        
        /// <summary>
        /// 建構一空的 CSTEQPWOAssignInfo 物件, 此 Ctor 是供 Generator 使用, 請勿直接呼叫.
        /// </summary>
        public CSTEQPWOAssignInfo() { }
        
        /// <summary>
        /// 建構一新的 CSTEQPWOAssignInfo object，由指定的 CST_EQP_WO_ASSIGN_Row 為 Raw Row。
        /// 此 Ctor 只供內部程式呼叫使用, 不為 public ctor.
        /// </summary>
        [Obsolete("已被 InfoBase.Create method 取代")]
        protected internal CSTEQPWOAssignInfo(CST_EQP_WO_ASSIGN_Row row) : base(row) { }
        #endregion
        
     
		
    }
}

