//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;


using Ares.Cimes.IntelliService.DbTableRow;
using Ares.Cimes.IntelliService.DbTableSchema;

namespace Ares.Cimes.IntelliService.Info
{
    /// <summary>
    ///  (Mapping CST_MMS_IQC_INFO Table)
    /// </summary>
    [Serializable]
    public partial class CSTMMSIqcInfo : InfoBase 
    {
        private static readonly CSTMMSIqcInfo s_ProxyInfo;
        
        
        
        private CST_MMS_IQC_INFO_Row m_StrongTypeRow { get { return (CST_MMS_IQC_INFO_Row)GetSchemaRow(); } }

        /// <summary>
        /// Non-Static Proxy Info Get Property
        /// </summary>        
        protected override InfoBase ProxyInfo { get { return s_ProxyInfo; } }

        #region Properties
        /// <summary>
        /// IQCTIME
        /// </summary>
        protected override DataColumn IDColumn { get { return CST_MMS_IQC_INFO.IQCTIME; } }
        
                /// <summary>
        /// IQC資訊系統編號 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String MMS_IQC_INFO_SID 
        {
            get { return m_StrongTypeRow.MMS_IQC_INFO_SID; }
            set { m_StrongTypeRow.MMS_IQC_INFO_SID = value; }
        }
        /// <summary>
        /// 來料爐號 資料型態:NVARCHAR2(100) 是否允許Null:N 
        /// </summary>
        public String RUNID 
        {
            get { return m_StrongTypeRow.RUNID; }
            set { m_StrongTypeRow.RUNID = value; }
        }
        /// <summary>
        /// 來料批號 資料型態:NVARCHAR2(100) 是否允許Null:N 
        /// </summary>
        public String Lot 
        {
            get { return m_StrongTypeRow.LOT; }
            set { m_StrongTypeRow.LOT = value; }
        }
        /// <summary>
        /// 入廠日期 資料型態:NVARCHAR2(100) 是否允許Null:N 
        /// </summary>
        public String IQCTIME 
        {
            get { return m_StrongTypeRow.IQCTIME; }
            set { m_StrongTypeRow.IQCTIME = value; }
        }
        /// <summary>
        /// 物料號 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String MATERIALNO
        {
            get { return m_StrongTypeRow.MATERIALNO; }
            set { m_StrongTypeRow.MATERIALNO = value; }
        }
        /// <summary>
        /// 來料數量 資料型態:NUMBER(13) 是否允許Null:Y 
        /// </summary>
        public Decimal Quantity 
        {
            get { return m_StrongTypeRow.QUANTITY; }
            set { m_StrongTypeRow.QUANTITY = value; }
        }

                
        
        #endregion Properties

        #region Ctor(...)
        static CSTMMSIqcInfo()
        {
            CSTMMSIqcInfo info = new CSTMMSIqcInfo();
            info.SetSchemaRow(CST_MMS_IQC_INFO.NewRow());
            s_ProxyInfo = info;
        }
        
        /// <summary>
        /// 建構一空的 CSTMMSIqcInfo 物件, 此 Ctor 是供 Generator 使用, 請勿直接呼叫.
        /// </summary>
        public CSTMMSIqcInfo() { }
        
        /// <summary>
        /// 建構一新的 CSTMMSIqcInfo object，由指定的 CST_MMS_IQC_INFO_Row 為 Raw Row。
        /// 此 Ctor 只供內部程式呼叫使用, 不為 public ctor.
        /// </summary>
        [Obsolete("已被 InfoBase.Create method 取代")]
        protected internal CSTMMSIqcInfo(CST_MMS_IQC_INFO_Row row) : base(row) { }
        #endregion
        
     
		
    }
}

