//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;


using Ares.Cimes.IntelliService.DbTableRow;
using Ares.Cimes.IntelliService.DbTableSchema;

namespace Ares.Cimes.IntelliService.Info
{
    /// <summary>
    /// ERP與MES站點對應明細 (Mapping CST_PRC_OPER_MAPPING_DATA Table)
    /// </summary>
    [Serializable]
    public partial class CSTPRCOperationMappingDataInfo : InfoBase 
    {
        private static readonly CSTPRCOperationMappingDataInfo s_ProxyInfo;
        
        
        
        private CST_PRC_OPER_MAPPING_DATA_Row m_StrongTypeRow { get { return (CST_PRC_OPER_MAPPING_DATA_Row)GetSchemaRow(); } }

        /// <summary>
        /// Non-Static Proxy Info Get Property
        /// </summary>        
        protected override InfoBase ProxyInfo { get { return s_ProxyInfo; } }

        #region Properties
        /// <summary>
        /// PRC_OPER_MAPPING_DATA_SID
        /// </summary>
        protected override DataColumn IDColumn { get { return CST_PRC_OPER_MAPPING_DATA.PRC_OPER_MAPPING_DATA_SID; } }
        
                /// <summary>
        /// ERP與MES站點對應明細SID 資料型態:NVARCHAR2(100) 是否允許Null:N 
        /// </summary>
        public String PRCOperationMappingDataSID 
        {
            get { return m_StrongTypeRow.PRC_OPER_MAPPING_DATA_SID; }
            set { m_StrongTypeRow.PRC_OPER_MAPPING_DATA_SID = value; }
        }
        /// <summary>
        /// ERP與MES站點對應主檔SID 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String PRCOperationMappingSID 
        {
            get { return m_StrongTypeRow.PRC_OPER_MAPPING_SID; }
            set { m_StrongTypeRow.PRC_OPER_MAPPING_SID = value; }
        }
        /// <summary>
        /// 站點順序 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String OperationSequence 
        {
            get { return m_StrongTypeRow.OPERSEQ; }
            set { m_StrongTypeRow.OPERSEQ = value; }
        }
        /// <summary>
        /// MES站點名稱 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String MESOperation 
        {
            get { return m_StrongTypeRow.MESOPER; }
            set { m_StrongTypeRow.MESOPER = value; }
        }
        /// <summary>
        /// 說明 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String OperationDescription 
        {
            get { return m_StrongTypeRow.OPERDESCR; }
            set { m_StrongTypeRow.OPERDESCR = value; }
        }
        /// <summary>
        /// 流程客製站點 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String CustomizePath
        {
            get { return m_StrongTypeRow.CUSTPATH; }
            set { m_StrongTypeRow.CUSTPATH = value; }
        }


        /// <summary>
        /// User ID
        /// </summary>
        public override string UserID { get { return m_StrongTypeRow.USERID; } protected set { m_StrongTypeRow.USERID = value; } }
        
        /// <summary>
        /// Update Time
        /// </summary>
        public override string UpdateTime { get { return m_StrongTypeRow.UPDATETIME; } protected set { m_StrongTypeRow.UPDATETIME = value; } }
        #endregion Properties

        #region Ctor(...)
        static CSTPRCOperationMappingDataInfo()
        {
            CSTPRCOperationMappingDataInfo info = new CSTPRCOperationMappingDataInfo();
            info.SetSchemaRow(CST_PRC_OPER_MAPPING_DATA.NewRow());
            s_ProxyInfo = info;
        }
        
        /// <summary>
        /// 建構一空的 CSTPRCOperationMappingDataInfo 物件, 此 Ctor 是供 Generator 使用, 請勿直接呼叫.
        /// </summary>
        public CSTPRCOperationMappingDataInfo() { }
        
        /// <summary>
        /// 建構一新的 CSTPRCOperationMappingDataInfo object，由指定的 CST_PRC_OPER_MAPPING_DATA_Row 為 Raw Row。
        /// 此 Ctor 只供內部程式呼叫使用, 不為 public ctor.
        /// </summary>
        [Obsolete("已被 InfoBase.Create method 取代")]
        protected internal CSTPRCOperationMappingDataInfo(CST_PRC_OPER_MAPPING_DATA_Row row) : base(row) { }
        #endregion
        
     
		
    }
}

