//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;


using Ares.Cimes.IntelliService.DbTableRow;
using Ares.Cimes.IntelliService.DbTableSchema;

namespace Ares.Cimes.IntelliService.Info
{
    /// <summary>
    /// ERP與MES站點對應主檔 (Mapping CST_PRC_OPER_MAPPING Table)
    /// </summary>
    [Serializable]
    public partial class CSTPRCOperationMappingInfo : InfoBase 
    {
        private static readonly CSTPRCOperationMappingInfo s_ProxyInfo;
        
        
        
        private CST_PRC_OPER_MAPPING_Row m_StrongTypeRow { get { return (CST_PRC_OPER_MAPPING_Row)GetSchemaRow(); } }

        /// <summary>
        /// Non-Static Proxy Info Get Property
        /// </summary>        
        protected override InfoBase ProxyInfo { get { return s_ProxyInfo; } }

        #region Properties
        /// <summary>
        /// PRC_OPER_MAPPING_SID
        /// </summary>
        protected override DataColumn IDColumn { get { return CST_PRC_OPER_MAPPING.PRC_OPER_MAPPING_SID; } }
        
                /// <summary>
        /// ERP與MES站點對應主檔SID 資料型態:NVARCHAR2(100) 是否允許Null:N 
        /// </summary>
        public String PRCOperationMappingSID 
        {
            get { return m_StrongTypeRow.PRC_OPER_MAPPING_SID; }
            set { m_StrongTypeRow.PRC_OPER_MAPPING_SID = value; }
        }
        /// <summary>
        /// ERP站點 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String ERPOperation 
        {
            get { return m_StrongTypeRow.ERPOPER; }
            set { m_StrongTypeRow.ERPOPER = value; }
        }
        /// <summary>
        /// 說明 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String Description 
        {
            get { return m_StrongTypeRow.DESCR; }
            set { m_StrongTypeRow.DESCR = value; }
        }
        /// <summary>
        /// 啟用狀態 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String Status 
        {
            get { return m_StrongTypeRow.STATUS; }
            set { m_StrongTypeRow.STATUS = value; }
        }
        /// <summary>
        /// 是否啟用 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String ActiveFlag 
        {
            get { return m_StrongTypeRow.ACTIVEFLAG; }
            set { m_StrongTypeRow.ACTIVEFLAG = value; }
        }

                
        /// <summary>
        /// User ID
        /// </summary>
        public override string UserID { get { return m_StrongTypeRow.USERID; } protected set { m_StrongTypeRow.USERID = value; } }
        
        /// <summary>
        /// Update Time
        /// </summary>
        public override string UpdateTime { get { return m_StrongTypeRow.UPDATETIME; } protected set { m_StrongTypeRow.UPDATETIME = value; } }
        #endregion Properties

        #region Ctor(...)
        static CSTPRCOperationMappingInfo()
        {
            CSTPRCOperationMappingInfo info = new CSTPRCOperationMappingInfo();
            info.SetSchemaRow(CST_PRC_OPER_MAPPING.NewRow());
            s_ProxyInfo = info;
        }
        
        /// <summary>
        /// 建構一空的 CSTPRCOperationMappingInfo 物件, 此 Ctor 是供 Generator 使用, 請勿直接呼叫.
        /// </summary>
        public CSTPRCOperationMappingInfo() { }
        
        /// <summary>
        /// 建構一新的 CSTPRCOperationMappingInfo object，由指定的 CST_PRC_OPER_MAPPING_Row 為 Raw Row。
        /// 此 Ctor 只供內部程式呼叫使用, 不為 public ctor.
        /// </summary>
        [Obsolete("已被 InfoBase.Create method 取代")]
        protected internal CSTPRCOperationMappingInfo(CST_PRC_OPER_MAPPING_Row row) : base(row) { }
        #endregion
        
     
		
    }
}

