//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;


using Ares.Cimes.IntelliService.DbTableRow;
using Ares.Cimes.IntelliService.DbTableSchema;

namespace Ares.Cimes.IntelliService.Info
{
    /// <summary>
    /// 線別工位設定主檔 (Mapping CST_PRC_LINE Table)
    /// </summary>
    [Serializable]
    public partial class CSTPrcLineInfo : InfoBase 
    {
        private static readonly CSTPrcLineInfo s_ProxyInfo;
        
        
        
        private CST_PRC_LINE_Row m_StrongTypeRow { get { return (CST_PRC_LINE_Row)GetSchemaRow(); } }

        /// <summary>
        /// Non-Static Proxy Info Get Property
        /// </summary>        
        protected override InfoBase ProxyInfo { get { return s_ProxyInfo; } }

        #region Properties
        /// <summary>
        /// PRC_LINE_SID
        /// </summary>
        protected override DataColumn IDColumn { get { return CST_PRC_LINE.PRC_LINE_SID; } }
        
                /// <summary>
        /// 線別工位設定主檔SID 資料型態:NVARCHAR2(100) 是否允許Null:N 
        /// </summary>
        public String PRC_LINE_SID 
        {
            get { return m_StrongTypeRow.PRC_LINE_SID; }
            set { m_StrongTypeRow.PRC_LINE_SID = value; }
        }
        /// <summary>
        /// 線別 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String Line 
        {
            get { return m_StrongTypeRow.LINE; }
            set { m_StrongTypeRow.LINE = value; }
        }
        /// <summary>
        /// 線別說明 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String Description 
        {
            get { return m_StrongTypeRow.DESCR; }
            set { m_StrongTypeRow.DESCR = value; }
        }
        /// <summary>
        /// 啟用狀態 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String Status 
        {
            get { return m_StrongTypeRow.STATUS; }
            set { m_StrongTypeRow.STATUS = value; }
        }
        /// <summary>
        /// 是否啟用 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String ActiveFlag 
        {
            get { return m_StrongTypeRow.ACTIVEFLAG; }
            set { m_StrongTypeRow.ACTIVEFLAG = value; }
        }

                
        /// <summary>
        /// User ID
        /// </summary>
        public override string UserID { get { return m_StrongTypeRow.USERID; } protected set { m_StrongTypeRow.USERID = value; } }
        
        /// <summary>
        /// Update Time
        /// </summary>
        public override string UpdateTime { get { return m_StrongTypeRow.UPDATETIME; } protected set { m_StrongTypeRow.UPDATETIME = value; } }
        #endregion Properties

        #region Ctor(...)
        static CSTPrcLineInfo()
        {
            CSTPrcLineInfo info = new CSTPrcLineInfo();
            info.SetSchemaRow(CST_PRC_LINE.NewRow());
            s_ProxyInfo = info;
        }
        
        /// <summary>
        /// 建構一空的 CSTPrcLineInfo 物件, 此 Ctor 是供 Generator 使用, 請勿直接呼叫.
        /// </summary>
        public CSTPrcLineInfo() { }
        
        /// <summary>
        /// 建構一新的 CSTPrcLineInfo object，由指定的 CST_PRC_LINE_Row 為 Raw Row。
        /// 此 Ctor 只供內部程式呼叫使用, 不為 public ctor.
        /// </summary>
        [Obsolete("已被 InfoBase.Create method 取代")]
        protected internal CSTPrcLineInfo(CST_PRC_LINE_Row row) : base(row) { }
        #endregion
        
     
		
    }
}

