//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;


using Ares.Cimes.IntelliService.DbTableRow;
using Ares.Cimes.IntelliService.DbTableSchema;

namespace Ares.Cimes.IntelliService.Info
{
    /// <summary>
    /// LOADER的解析紀錄表 (Mapping CST_SYS_LOADER_LOG Table)
    /// </summary>
    [Serializable]
    public partial class CSTSystemLoaderLogInfo : InfoBase 
    {
        private static readonly CSTSystemLoaderLogInfo s_ProxyInfo;
        
        
        
        private CST_SYS_LOADER_LOG_Row m_StrongTypeRow { get { return (CST_SYS_LOADER_LOG_Row)GetSchemaRow(); } }

        /// <summary>
        /// Non-Static Proxy Info Get Property
        /// </summary>        
        protected override InfoBase ProxyInfo { get { return s_ProxyInfo; } }

        #region Properties
        /// <summary>
        /// #SIDColumnName
        /// </summary>
        protected override DataColumn IDColumn { get { return CST_SYS_LOADER_LOG.SYS_LOADER_LOG; } }
        
                /// <summary>
        /// LOADER解析紀錄表SID 資料型態:NVARCHAR2(200) 是否允許Null:Y 
        /// </summary>
        public String SystemLoaderLog 
        {
            get { return m_StrongTypeRow.SYS_LOADER_LOG; }
            set { m_StrongTypeRow.SYS_LOADER_LOG = value; }
        }
        /// <summary>
        /// 主要鍵值(序號/鍛造批號/小工單號) 資料型態:NVARCHAR2(200) 是否允許Null:Y 
        /// </summary>
        public String Item 
        {
            get { return m_StrongTypeRow.ITEM; }
            set { m_StrongTypeRow.ITEM = value; }
        }
        /// <summary>
        /// LOADER名稱 資料型態:NVARCHAR2(200) 是否允許Null:Y 
        /// </summary>
        public String ItemType 
        {
            get { return m_StrongTypeRow.ITEM_TYPE; }
            set { m_StrongTypeRow.ITEM_TYPE = value; }
        }
        /// <summary>
        /// 解析的檔案名稱 資料型態:NVARCHAR2(200) 是否允許Null:Y 
        /// </summary>
        public String ItemFile 
        {
            get { return m_StrongTypeRow.ITEM_FILE; }
            set { m_StrongTypeRow.ITEM_FILE = value; }
        }
        /// <summary>
        /// 檔案解析的結果(OK / NG) 資料型態:NVARCHAR2(200) 是否允許Null:Y 
        /// </summary>
        public String Result 
        {
            get { return m_StrongTypeRow.RESULT; }
            set { m_StrongTypeRow.RESULT = value; }
        }
        /// <summary>
        /// 解析成功紀錄SUCCESSFUL，失敗就紀錄ERROR原因 資料型態:NVARCHAR2(2000) 是否允許Null:Y 
        /// </summary>
        public String Message 
        {
            get { return m_StrongTypeRow.MESSAGE; }
            set { m_StrongTypeRow.MESSAGE = value; }
        }
        /// <summary>
        /// 紀錄LOG的時間 資料型態:NVARCHAR2(200) 是否允許Null:Y 
        /// </summary>
        public String Rectime 
        {
            get { return m_StrongTypeRow.RECTIME; }
            set { m_StrongTypeRow.RECTIME = value; }
        }

                
        ///// <summary>
        ///// User ID
        ///// </summary>
        //public override string UserID { get { return m_StrongTypeRow.USERID; } protected set { m_StrongTypeRow.USERID = value; } }
        
        ///// <summary>
        ///// Update Time
        ///// </summary>
        //public override string UpdateTime { get { return m_StrongTypeRow.UPDATETIME; } protected set { m_StrongTypeRow.UPDATETIME = value; } }
        #endregion Properties

        #region Ctor(...)
        static CSTSystemLoaderLogInfo()
        {
            CSTSystemLoaderLogInfo info = new CSTSystemLoaderLogInfo();
            info.SetSchemaRow(CST_SYS_LOADER_LOG.NewRow());
            s_ProxyInfo = info;
        }
        
        /// <summary>
        /// 建構一空的 CSTSystemLoaderLogInfo 物件, 此 Ctor 是供 Generator 使用, 請勿直接呼叫.
        /// </summary>
        public CSTSystemLoaderLogInfo() { }
        
        /// <summary>
        /// 建構一新的 CSTSystemLoaderLogInfo object，由指定的 CST_SYS_LOADER_LOG_Row 為 Raw Row。
        /// 此 Ctor 只供內部程式呼叫使用, 不為 public ctor.
        /// </summary>
        [Obsolete("已被 InfoBase.Create method 取代")]
        protected internal CSTSystemLoaderLogInfo(CST_SYS_LOADER_LOG_Row row) : base(row) { }
        #endregion
        
     
		
    }
}

