//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;


using Ares.Cimes.IntelliService.DbTableRow;
using Ares.Cimes.IntelliService.DbTableSchema;

namespace Ares.Cimes.IntelliService.Info
{
    /// <summary>
    /// 刀具標籤列印紀錄 (Mapping CST_TOOL_LABEL_PRINT_LOG Table)
    /// </summary>
    [Serializable]
    public partial class CSTToolLabelPrintLogInfo : InfoBase 
    {
        private static readonly CSTToolLabelPrintLogInfo s_ProxyInfo;
        
        
        
        private CST_TOOL_LABEL_PRINT_LOG_Row m_StrongTypeRow { get { return (CST_TOOL_LABEL_PRINT_LOG_Row)GetSchemaRow(); } }

        /// <summary>
        /// Non-Static Proxy Info Get Property
        /// </summary>        
        protected override InfoBase ProxyInfo { get { return s_ProxyInfo; } }

        #region Properties
        /// <summary>
        /// TOOL_LABEL_PRINT_LOG
        /// </summary>
        protected override DataColumn IDColumn { get { return CST_TOOL_LABEL_PRINT_LOG.TOOL_LABEL_PRINT_LOG; } }
        
                /// <summary>
        /// 刀具標籤列印紀錄表SID 資料型態:NVARCHAR2(100) 是否允許Null:N 
        /// </summary>
        public String TOOL_LABEL_PRINT_LOG 
        {
            get { return m_StrongTypeRow.TOOL_LABEL_PRINT_LOG; }
            set { m_StrongTypeRow.TOOL_LABEL_PRINT_LOG = value; }
        }
        /// <summary>
        /// 刀具 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String ToolName 
        {
            get { return m_StrongTypeRow.TOOLNAME; }
            set { m_StrongTypeRow.TOOLNAME = value; }
        }
        /// <summary>
        /// 列印功能名稱 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String RuleName 
        {
            get { return m_StrongTypeRow.RULENAME; }
            set { m_StrongTypeRow.RULENAME = value; }
        }

                
        /// <summary>
        /// User ID
        /// </summary>
        public override string UserID { get { return m_StrongTypeRow.USERID; } protected set { m_StrongTypeRow.USERID = value; } }
        
        /// <summary>
        /// Update Time
        /// </summary>
        public override string UpdateTime { get { return m_StrongTypeRow.UPDATETIME; } protected set { m_StrongTypeRow.UPDATETIME = value; } }
        #endregion Properties

        #region Ctor(...)
        static CSTToolLabelPrintLogInfo()
        {
            CSTToolLabelPrintLogInfo info = new CSTToolLabelPrintLogInfo();
            info.SetSchemaRow(CST_TOOL_LABEL_PRINT_LOG.NewRow());
            s_ProxyInfo = info;
        }
        
        /// <summary>
        /// 建構一空的 CSTToolLabelPrintLogInfo 物件, 此 Ctor 是供 Generator 使用, 請勿直接呼叫.
        /// </summary>
        public CSTToolLabelPrintLogInfo() { }
        
        /// <summary>
        /// 建構一新的 CSTToolLabelPrintLogInfo object，由指定的 CST_TOOL_LABEL_PRINT_LOG_Row 為 Raw Row。
        /// 此 Ctor 只供內部程式呼叫使用, 不為 public ctor.
        /// </summary>
        [Obsolete("已被 InfoBase.Create method 取代")]
        protected internal CSTToolLabelPrintLogInfo(CST_TOOL_LABEL_PRINT_LOG_Row row) : base(row) { }
        #endregion
        
     
		
    }
}

