//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;


using Ares.Cimes.IntelliService.DbTableRow;
using Ares.Cimes.IntelliService.DbTableSchema;

namespace Ares.Cimes.IntelliService.Info
{
    /// <summary>
    /// 刀具檢驗報告資訊紀錄表 (Mapping CST_TOOL_REPORT_LOG Table)
    /// </summary>
    [Serializable]
    public partial class CSTToolReportLogInfo : InfoBase 
    {
        private static readonly CSTToolReportLogInfo s_ProxyInfo;
        
        
        
        private CST_TOOL_REPORT_LOG_Row m_StrongTypeRow { get { return (CST_TOOL_REPORT_LOG_Row)GetSchemaRow(); } }

        /// <summary>
        /// Non-Static Proxy Info Get Property
        /// </summary>        
        protected override InfoBase ProxyInfo { get { return s_ProxyInfo; } }

        #region Properties
        /// <summary>
        /// #SIDColumnName
        /// </summary>
        protected override DataColumn IDColumn { get { return CST_TOOL_REPORT_LOG.TOOL_REPORT_LOG_SID; } }
        
                /// <summary>
        /// 刀具檢驗報告資訊紀錄表 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String ToolReportLogSID 
        {
            get { return m_StrongTypeRow.TOOL_REPORT_LOG_SID; }
            set { m_StrongTypeRow.TOOL_REPORT_LOG_SID = value; }
        }
        /// <summary>
        /// 刀具檢驗報告資訊表SID 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String ToolReportSID 
        {
            get { return m_StrongTypeRow.TOOL_REPORT_SID; }
            set { m_StrongTypeRow.TOOL_REPORT_SID = value; }
        }
        /// <summary>
        /// 刀具名稱 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String ToolName 
        {
            get { return m_StrongTypeRow.TOOLNAME; }
            set { m_StrongTypeRow.TOOLNAME = value; }
        }
        /// <summary>
        /// 檔案名稱 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String FileName 
        {
            get { return m_StrongTypeRow.FILENAME; }
            set { m_StrongTypeRow.FILENAME = value; }
        }
        /// <summary>
        /// 交易範疇識別碼 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String TXNSCOPEUID 
        {
            get { return m_StrongTypeRow.TXNSCOPEUID; }
            set { m_StrongTypeRow.TXNSCOPEUID = value; }
        }
        /// <summary>
        /// 交易行為 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String ACTIONTYPE 
        {
            get { return m_StrongTypeRow.ACTIONTYPE; }
            set { m_StrongTypeRow.ACTIONTYPE = value; }
        }
        /// <summary>
        /// 執行的應用程式名稱 (Rule路徑+ClientIP: SessionID) 資料型態:NVARCHAR2(2000) 是否允許Null:Y 
        /// </summary>
        public String APPLICATIONNAME 
        {
            get { return m_StrongTypeRow.APPLICATIONNAME; }
            set { m_StrongTypeRow.APPLICATIONNAME = value; }
        }

                
        /// <summary>
        /// User ID
        /// </summary>
        public override string UserID { get { return m_StrongTypeRow.USERID; } protected set { m_StrongTypeRow.USERID = value; } }
        
        /// <summary>
        /// Update Time
        /// </summary>
        public override string UpdateTime { get { return m_StrongTypeRow.UPDATETIME; } protected set { m_StrongTypeRow.UPDATETIME = value; } }
        #endregion Properties

        #region Ctor(...)
        static CSTToolReportLogInfo()
        {
            CSTToolReportLogInfo info = new CSTToolReportLogInfo();
            info.SetSchemaRow(CST_TOOL_REPORT_LOG.NewRow());
            s_ProxyInfo = info;
        }
        
        /// <summary>
        /// 建構一空的 CSTToolReportLogInfo 物件, 此 Ctor 是供 Generator 使用, 請勿直接呼叫.
        /// </summary>
        public CSTToolReportLogInfo() { }
        
        /// <summary>
        /// 建構一新的 CSTToolReportLogInfo object，由指定的 CST_TOOL_REPORT_LOG_Row 為 Raw Row。
        /// 此 Ctor 只供內部程式呼叫使用, 不為 public ctor.
        /// </summary>
        [Obsolete("已被 InfoBase.Create method 取代")]
        protected internal CSTToolReportLogInfo(CST_TOOL_REPORT_LOG_Row row) : base(row) { }
        #endregion
        
     
		
    }
}

