//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;


using Ares.Cimes.IntelliService.DbTableRow;
using Ares.Cimes.IntelliService.DbTableSchema;

namespace Ares.Cimes.IntelliService.Info
{
    /// <summary>
    /// 刀具維修時壽命表 (Mapping CST_TOOL_REPAIR_LIFE Table)
    /// </summary>
    [Serializable]
    public partial class CSTToolRepairLifeInfo : InfoBase 
    {
        private static readonly CSTToolRepairLifeInfo s_ProxyInfo;
        
        
        
        private CST_TOOL_REPAIR_LIFE_Row m_StrongTypeRow { get { return (CST_TOOL_REPAIR_LIFE_Row)GetSchemaRow(); } }

        /// <summary>
        /// Non-Static Proxy Info Get Property
        /// </summary>        
        protected override InfoBase ProxyInfo { get { return s_ProxyInfo; } }

        #region Properties
        /// <summary>
        /// TOOL_REPAIR_LIFE_SID
        /// </summary>
        protected override DataColumn IDColumn { get { return CST_TOOL_REPAIR_LIFE.TOOL_REPAIR_LIFE_SID; } }
        
                /// <summary>
        /// 刀具維修時壽命表SID 資料型態:NVARCHAR2(100) 是否允許Null:N 
        /// </summary>
        public String ToolRepairLifeSID 
        {
            get { return m_StrongTypeRow.TOOL_REPAIR_LIFE_SID; }
            set { m_StrongTypeRow.TOOL_REPAIR_LIFE_SID = value; }
        }
        /// <summary>
        /// 紀錄維修回廠資訊表ID 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String ToolRepairSID 
        {
            get { return m_StrongTypeRow.TOOL_REPAIR_SID; }
            set { m_StrongTypeRow.TOOL_REPAIR_SID = value; }
        }
        /// <summary>
        /// 刀面 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String Head 
        {
            get { return m_StrongTypeRow.HEAD; }
            set { m_StrongTypeRow.HEAD = value; }
        }
        /// <summary>
        /// 使用壽命 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String Life 
        {
            get { return m_StrongTypeRow.LIFE; }
            set { m_StrongTypeRow.LIFE = value; }
        }

                
        ///// <summary>
        ///// User ID
        ///// </summary>
        //public override string UserID { get { return m_StrongTypeRow.USERID; } protected set { m_StrongTypeRow.USERID = value; } }
        
        ///// <summary>
        ///// Update Time
        ///// </summary>
        //public override string UpdateTime { get { return m_StrongTypeRow.UPDATETIME; } protected set { m_StrongTypeRow.UPDATETIME = value; } }
        #endregion Properties

        #region Ctor(...)
        static CSTToolRepairLifeInfo()
        {
            CSTToolRepairLifeInfo info = new CSTToolRepairLifeInfo();
            info.SetSchemaRow(CST_TOOL_REPAIR_LIFE.NewRow());
            s_ProxyInfo = info;
        }
        
        /// <summary>
        /// 建構一空的 CSTToolRepairLifeInfo 物件, 此 Ctor 是供 Generator 使用, 請勿直接呼叫.
        /// </summary>
        public CSTToolRepairLifeInfo() { }
        
        /// <summary>
        /// 建構一新的 CSTToolRepairLifeInfo object，由指定的 CST_TOOL_REPAIR_LIFE_Row 為 Raw Row。
        /// 此 Ctor 只供內部程式呼叫使用, 不為 public ctor.
        /// </summary>
        [Obsolete("已被 InfoBase.Create method 取代")]
        protected internal CSTToolRepairLifeInfo(CST_TOOL_REPAIR_LIFE_Row row) : base(row) { }
        #endregion
        
     
		
    }
}

