//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;


using Ares.Cimes.IntelliService.DbTableRow;
using Ares.Cimes.IntelliService.DbTableSchema;

namespace Ares.Cimes.IntelliService.Info
{
    /// <summary>
    ///  (Mapping CST_TOOL_TYPE_PICT_LOG Table)
    /// </summary>
    [Serializable]
    public partial class CSTToolTypePictureLogInfo : InfoBase 
    {
        private static readonly CSTToolTypePictureLogInfo s_ProxyInfo;
        
        
        
        private CST_TOOL_TYPE_PICT_LOG_Row m_StrongTypeRow { get { return (CST_TOOL_TYPE_PICT_LOG_Row)GetSchemaRow(); } }

        /// <summary>
        /// Non-Static Proxy Info Get Property
        /// </summary>        
        protected override InfoBase ProxyInfo { get { return s_ProxyInfo; } }

        #region Properties
        /// <summary>
        /// #SIDColumnName
        /// </summary>
        protected override DataColumn IDColumn { get { return CST_TOOL_TYPE_PICT_LOG.TOOL_TYPE_PICT_HIST_SID; } }
        
                /// <summary>
        ///  資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String ToolTypeLifePictureLogSID 
        {
            get { return m_StrongTypeRow.TOOL_TYPE_PICT_HIST_SID; }
            set { m_StrongTypeRow.TOOL_TYPE_PICT_HIST_SID = value; }
        }
        /// <summary>
        ///  資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String ToolTypePictureSID 
        {
            get { return m_StrongTypeRow.TOOL_TYPE_PICT_SID; }
            set { m_StrongTypeRow.TOOL_TYPE_PICT_SID = value; }
        }
        /// <summary>
        ///  資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String ToolType 
        {
            get { return m_StrongTypeRow.TOOLTYPE; }
            set { m_StrongTypeRow.TOOLTYPE = value; }
        }
        /// <summary>
        ///  資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String FileName 
        {
            get { return m_StrongTypeRow.FILENAME; }
            set { m_StrongTypeRow.FILENAME = value; }
        }

                
        /// <summary>
        /// User ID
        /// </summary>
        public override string UserID { get { return m_StrongTypeRow.USERID; } protected set { m_StrongTypeRow.USERID = value; } }
        
        /// <summary>
        /// Update Time
        /// </summary>
        public override string UpdateTime { get { return m_StrongTypeRow.UPDATETIME; } protected set { m_StrongTypeRow.UPDATETIME = value; } }
        #endregion Properties

        #region Ctor(...)
        static CSTToolTypePictureLogInfo()
        {
            CSTToolTypePictureLogInfo info = new CSTToolTypePictureLogInfo();
            info.SetSchemaRow(CST_TOOL_TYPE_PICT_LOG.NewRow());
            s_ProxyInfo = info;
        }

        /// <summary>
        /// 建構一空的 CSTToolTypePictureLogInfo 物件, 此 Ctor 是供 Generator 使用, 請勿直接呼叫.
        /// </summary>
        public CSTToolTypePictureLogInfo() { }

        /// <summary>
        /// 建構一新的 CSTToolTypePictureLogInfo object，由指定的 CST_TOOL_TYPE_PICT_LOG_Row 為 Raw Row。
        /// 此 Ctor 只供內部程式呼叫使用, 不為 public ctor.
        /// </summary>
        [Obsolete("已被 InfoBase.Create method 取代")]
        protected internal CSTToolTypePictureLogInfo(CST_TOOL_TYPE_PICT_LOG_Row row) : base(row) { }
        #endregion
        
     
		
    }
}

