//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;


using Ares.Cimes.IntelliService.DbTableRow;
using Ares.Cimes.IntelliService.DbTableSchema;

namespace Ares.Cimes.IntelliService.Info
{
    /// <summary>
    /// 刀具領用表 (Mapping CST_TOOL_ISSUE Table)
    /// </summary>
    [Serializable]
    public partial class CSTToolIssueInfo : InfoBase 
    {
        private static readonly CSTToolIssueInfo s_ProxyInfo;
        
        
        
        private CST_TOOL_ISSUE_Row m_StrongTypeRow { get { return (CST_TOOL_ISSUE_Row)GetSchemaRow(); } }

        /// <summary>
        /// Non-Static Proxy Info Get Property
        /// </summary>        
        protected override InfoBase ProxyInfo { get { return s_ProxyInfo; } }

        #region Properties
        /// <summary>
        /// #SIDColumnName
        /// </summary>
        protected override DataColumn IDColumn { get { return CST_TOOL_ISSUE.TOOL_ISSUE_SID; } }
        
                /// <summary>
        /// 刀具領用表SID 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String TOOL_ISSUE_SID 
        {
            get { return m_StrongTypeRow.TOOL_ISSUE_SID; }
            set { m_StrongTypeRow.TOOL_ISSUE_SID = value; }
        }
        /// <summary>
        /// 領用總數量 資料型態:NUMBER(38) 是否允許Null:Y 
        /// </summary>
        public Decimal TOTALQTY 
        {
            get { return m_StrongTypeRow.TOTALQTY; }
            set { m_StrongTypeRow.TOTALQTY = value; }
        }
        /// <summary>
        /// 領用原因 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String Reason 
        {
            get { return m_StrongTypeRow.REASON; }
            set { m_StrongTypeRow.REASON = value; }
        }
        /// <summary>
        /// 領用說明 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String Description 
        {
            get { return m_StrongTypeRow.DESCR; }
            set { m_StrongTypeRow.DESCR = value; }
        }
        /// <summary>
        /// 領用機台 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String EquipmentName 
        {
            get { return m_StrongTypeRow.EQP; }
            set { m_StrongTypeRow.EQP = value; }
        }
        /// <summary>
        /// 交易繫結SID 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String LinkSID 
        {
            get { return m_StrongTypeRow.LINKSID; }
            set { m_StrongTypeRow.LINKSID = value; }
        }
        /// <summary>
        /// 交易動作 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String Action 
        {
            get { return m_StrongTypeRow.ACTION; }
            set { m_StrongTypeRow.ACTION = value; }
        }

                
        /// <summary>
        /// User ID
        /// </summary>
        public override string UserID { get { return m_StrongTypeRow.USERID; } protected set { m_StrongTypeRow.USERID = value; } }
        
        /// <summary>
        /// Update Time
        /// </summary>
        public override string UpdateTime { get { return m_StrongTypeRow.UPDATETIME; } protected set { m_StrongTypeRow.UPDATETIME = value; } }
        #endregion Properties

        #region Ctor(...)
        static CSTToolIssueInfo()
        {
            CSTToolIssueInfo info = new CSTToolIssueInfo();
            info.SetSchemaRow(CST_TOOL_ISSUE.NewRow());
            s_ProxyInfo = info;
        }
        
        /// <summary>
        /// 建構一空的 CSTToolIssueInfo 物件, 此 Ctor 是供 Generator 使用, 請勿直接呼叫.
        /// </summary>
        public CSTToolIssueInfo() { }
        
        /// <summary>
        /// 建構一新的 CSTToolIssueInfo object，由指定的 CST_TOOL_ISSUE_Row 為 Raw Row。
        /// 此 Ctor 只供內部程式呼叫使用, 不為 public ctor.
        /// </summary>
        [Obsolete("已被 InfoBase.Create method 取代")]
        protected internal CSTToolIssueInfo(CST_TOOL_ISSUE_Row row) : base(row) { }
        #endregion
        
     
		
    }
}

