//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;


using Ares.Cimes.IntelliService.DbTableRow;
using Ares.Cimes.IntelliService.DbTableSchema;

namespace Ares.Cimes.IntelliService.Info
{
    /// <summary>
    /// 人員換班紀錄 (Mapping CST_USR_CHANGE_WORKTIME Table)
    /// </summary>
    [Serializable]
    public partial class CSTUserChangeWorktimeInfo : InfoBase 
    {
        private static readonly CSTUserChangeWorktimeInfo s_ProxyInfo;
        
        
        
        private CST_USR_CHANGE_WORKTIME_Row m_StrongTypeRow { get { return (CST_USR_CHANGE_WORKTIME_Row)GetSchemaRow(); } }

        /// <summary>
        /// Non-Static Proxy Info Get Property
        /// </summary>        
        protected override InfoBase ProxyInfo { get { return s_ProxyInfo; } }

        #region Properties
        /// <summary>
        /// USR_CHANGE_WORKTIME_SID
        /// </summary>
        protected override DataColumn IDColumn { get { return CST_USR_CHANGE_WORKTIME.USR_CHANGE_WORKTIME_SID; } }
        
                /// <summary>
        /// 人員換班紀錄表SID 資料型態:NVARCHAR2(100) 是否允許Null:N 
        /// </summary>
        public String USR_CHANGE_WORKTIME_SID 
        {
            get { return m_StrongTypeRow.USR_CHANGE_WORKTIME_SID; }
            set { m_StrongTypeRow.USR_CHANGE_WORKTIME_SID = value; }
        }
        /// <summary>
        /// 班別日期 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String SHIFTDATE 
        {
            get { return m_StrongTypeRow.SHIFTDATE; }
            set { m_StrongTypeRow.SHIFTDATE = value; }
        }
        /// <summary>
        /// 班別 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String SHIFT 
        {
            get { return m_StrongTypeRow.SHIFT; }
            set { m_StrongTypeRow.SHIFT = value; }
        }
        /// <summary>
        /// 批號 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String Lot 
        {
            get { return m_StrongTypeRow.LOT; }
            set { m_StrongTypeRow.LOT = value; }
        }
        /// <summary>
        /// 機台 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String EquipmentName 
        {
            get { return m_StrongTypeRow.EQUIPMENT; }
            set { m_StrongTypeRow.EQUIPMENT = value; }
        }
        /// <summary>
        /// 工作站 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String OperationName 
        {
            get { return m_StrongTypeRow.OPERATION; }
            set { m_StrongTypeRow.OPERATION = value; }
        }
        /// <summary>
        /// 數量 資料型態:NUMBER(13) 是否允許Null:Y 
        /// </summary>
        public Decimal Quantity 
        {
            get { return m_StrongTypeRow.QUANTITY; }
            set { m_StrongTypeRow.QUANTITY = value; }
        }
        /// <summary>
        /// 是否滿批 資料型態:NVARCHAR2(10) 是否允許Null:Y 
        /// </summary>
        public String FULLFLAG 
        {
            get { return m_StrongTypeRow.FULLFLAG; }
            set { m_StrongTypeRow.FULLFLAG = value; }
        }

                
        /// <summary>
        /// User ID
        /// </summary>
        public override string UserID { get { return m_StrongTypeRow.USERID; } protected set { m_StrongTypeRow.USERID = value; } }
        
        /// <summary>
        /// Update Time
        /// </summary>
        public override string UpdateTime { get { return m_StrongTypeRow.UPDATETIME; } protected set { m_StrongTypeRow.UPDATETIME = value; } }
        #endregion Properties

        #region Ctor(...)
        static CSTUserChangeWorktimeInfo()
        {
            CSTUserChangeWorktimeInfo info = new CSTUserChangeWorktimeInfo();
            info.SetSchemaRow(CST_USR_CHANGE_WORKTIME.NewRow());
            s_ProxyInfo = info;
        }
        
        /// <summary>
        /// 建構一空的 CSTUserChangeWorktimeInfo 物件, 此 Ctor 是供 Generator 使用, 請勿直接呼叫.
        /// </summary>
        public CSTUserChangeWorktimeInfo() { }
        
        /// <summary>
        /// 建構一新的 CSTUserChangeWorktimeInfo object，由指定的 CST_USR_CHANGE_WORKTIME_Row 為 Raw Row。
        /// 此 Ctor 只供內部程式呼叫使用, 不為 public ctor.
        /// </summary>
        [Obsolete("已被 InfoBase.Create method 取代")]
        protected internal CSTUserChangeWorktimeInfo(CST_USR_CHANGE_WORKTIME_Row row) : base(row) { }
        #endregion
        
     
		
    }
}

