//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;


using Ares.Cimes.IntelliService.DbTableRow;
using Ares.Cimes.IntelliService.DbTableSchema;

namespace Ares.Cimes.IntelliService.Info
{
    /// <summary>
    /// 人員上工現狀 (Mapping CST_USR_CURRENT_STATUS Table)
    /// </summary>
    [Serializable]
    public partial class CSTUserCurrentStatusInfo : InfoBase 
    {
        private static readonly CSTUserCurrentStatusInfo s_ProxyInfo;
        
        
        
        private CST_USR_CURRENT_STATUS_Row m_StrongTypeRow { get { return (CST_USR_CURRENT_STATUS_Row)GetSchemaRow(); } }

        /// <summary>
        /// Non-Static Proxy Info Get Property
        /// </summary>        
        protected override InfoBase ProxyInfo { get { return s_ProxyInfo; } }

        #region Properties
        /// <summary>
        /// USR_CURRENT_STATUS_SID
        /// </summary>
        protected override DataColumn IDColumn { get { return CST_USR_CURRENT_STATUS.USR_CURRENT_STATUS_SID; } }
        
                /// <summary>
        /// 人員上工系統編號 資料型態:NVARCHAR2(100) 是否允許Null:N 
        /// </summary>
        public String USR_CURRENT_STATUS_SID 
        {
            get { return m_StrongTypeRow.USR_CURRENT_STATUS_SID; }
            set { m_StrongTypeRow.USR_CURRENT_STATUS_SID = value; }
        }
        /// <summary>
        /// 機台編號 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String Line
        {
            get { return m_StrongTypeRow.LINE; }
            set { m_StrongTypeRow.LINE = value; }
        }
        /// <summary>
        /// 上工人員 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String WorkUserID
        {
            get { return m_StrongTypeRow.WORKUSERID; }
            set { m_StrongTypeRow.WORKUSERID = value; }
        }
        /// <summary>
        /// 工位 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String UserWorkPlace
        {
            get { return m_StrongTypeRow.USR_WORKPALCE; }
            set { m_StrongTypeRow.USR_WORKPALCE = value; }
        }
        /// <summary>
        /// 上工時間 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String WorkTime 
        {
            get { return m_StrongTypeRow.WORKTIME; }
            set { m_StrongTypeRow.WORKTIME = value; }
        }
        /// <summary>
        /// Up:人員上工，Down:人員下工 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String Action 
        {
            get { return m_StrongTypeRow.ACTION; }
            set { m_StrongTypeRow.ACTION = value; }
        }

                
        /// <summary>
        /// User ID
        /// </summary>
        public override string UserID { get { return m_StrongTypeRow.USERID; } protected set { m_StrongTypeRow.USERID = value; } }
        
        /// <summary>
        /// Update Time
        /// </summary>
        public override string UpdateTime { get { return m_StrongTypeRow.UPDATETIME; } protected set { m_StrongTypeRow.UPDATETIME = value; } }
        #endregion Properties

        #region Ctor(...)
        static CSTUserCurrentStatusInfo()
        {
            CSTUserCurrentStatusInfo info = new CSTUserCurrentStatusInfo();
            info.SetSchemaRow(CST_USR_CURRENT_STATUS.NewRow());
            s_ProxyInfo = info;
        }
        
        /// <summary>
        /// 建構一空的 CSTUserCurrentStatusInfo 物件, 此 Ctor 是供 Generator 使用, 請勿直接呼叫.
        /// </summary>
        public CSTUserCurrentStatusInfo() { }
        
        /// <summary>
        /// 建構一新的 CSTUserCurrentStatusInfo object，由指定的 CST_USR_CURRENT_STATUS_Row 為 Raw Row。
        /// 此 Ctor 只供內部程式呼叫使用, 不為 public ctor.
        /// </summary>
        [Obsolete("已被 InfoBase.Create method 取代")]
        protected internal CSTUserCurrentStatusInfo(CST_USR_CURRENT_STATUS_Row row) : base(row) { }
        #endregion
        
     
		
    }
}

