//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;


using Ares.Cimes.IntelliService.DbTableRow;
using Ares.Cimes.IntelliService.DbTableSchema;

namespace Ares.Cimes.IntelliService.Info
{
    /// <summary>
    ///  (Mapping CST_USR_EXCEPT_WORKTIME Table)
    /// </summary>
    [Serializable]
    public partial class CSTUserExceptWorktimeInfo : InfoBase 
    {
        private static readonly CSTUserExceptWorktimeInfo s_ProxyInfo;
        
        
        
        private CST_USR_EXCEPT_WORKTIME_Row m_StrongTypeRow { get { return (CST_USR_EXCEPT_WORKTIME_Row)GetSchemaRow(); } }

        /// <summary>
        /// Non-Static Proxy Info Get Property
        /// </summary>        
        protected override InfoBase ProxyInfo { get { return s_ProxyInfo; } }

        #region Properties
        /// <summary>
        /// USR_EXCEPT_WORKTIME_SID
        /// </summary>
        protected override DataColumn IDColumn { get { return CST_USR_EXCEPT_WORKTIME.USR_EXCEPT_WORKTIME_SID; } }
        
                /// <summary>
        /// 人员除外工时系统编号 資料型態:NVARCHAR2(100) 是否允許Null:N 
        /// </summary>
        public String USR_EXCEPT_WORKTIME_SID 
        {
            get { return m_StrongTypeRow.USR_EXCEPT_WORKTIME_SID; }
            set { m_StrongTypeRow.USR_EXCEPT_WORKTIME_SID = value; }
        }
        /// <summary>
        /// 除外人员 資料型態:NVARCHAR2(100) 是否允許Null:N 
        /// </summary>
        public String WORK_USERID 
        {
            get { return m_StrongTypeRow.WORK_USERID; }
            set { m_StrongTypeRow.WORK_USERID = value; }
        }
        /// <summary>
        /// 工作線別 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String WORK_LINE 
        {
            get { return m_StrongTypeRow.WORK_LINE; }
            set { m_StrongTypeRow.WORK_LINE = value; }
        }
        /// <summary>
        /// 除外原因 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String Reason 
        {
            get { return m_StrongTypeRow.REASON; }
            set { m_StrongTypeRow.REASON = value; }
        }
        /// <summary>
        /// 備註 資料型態:NVARCHAR2(2000) 是否允許Null:Y 
        /// </summary>
        public String Remark 
        {
            get { return m_StrongTypeRow.REMARK; }
            set { m_StrongTypeRow.REMARK = value; }
        }
        /// <summary>
        /// 开始时间 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String StartTime 
        {
            get { return m_StrongTypeRow.STARTTIME; }
            set { m_StrongTypeRow.STARTTIME = value; }
        }
        /// <summary>
        /// 结束时间 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String EndTime 
        {
            get { return m_StrongTypeRow.ENDTIME; }
            set { m_StrongTypeRow.ENDTIME = value; }
        }

                
        /// <summary>
        /// User ID
        /// </summary>
        //public override string UserID { get { return m_StrongTypeRow.USERID; } protected set { m_StrongTypeRow.USERID = value; } }
        
        /// <summary>
        /// Update Time
        /// </summary>
        //public override string UpdateTime { get { return m_StrongTypeRow.UPDATETIME; } protected set { m_StrongTypeRow.UPDATETIME = value; } }
        #endregion Properties

        #region Ctor(...)
        static CSTUserExceptWorktimeInfo()
        {
            CSTUserExceptWorktimeInfo info = new CSTUserExceptWorktimeInfo();
            info.SetSchemaRow(CST_USR_EXCEPT_WORKTIME.NewRow());
            s_ProxyInfo = info;
        }
        
        /// <summary>
        /// 建構一空的 CSTUserExceptWorktimeInfo 物件, 此 Ctor 是供 Generator 使用, 請勿直接呼叫.
        /// </summary>
        public CSTUserExceptWorktimeInfo() { }
        
        /// <summary>
        /// 建構一新的 CSTUserExceptWorktimeInfo object，由指定的 CST_USR_EXCEPT_WORKTIME_Row 為 Raw Row。
        /// 此 Ctor 只供內部程式呼叫使用, 不為 public ctor.
        /// </summary>
        [Obsolete("已被 InfoBase.Create method 取代")]
        protected internal CSTUserExceptWorktimeInfo(CST_USR_EXCEPT_WORKTIME_Row row) : base(row) { }
        #endregion
        
     
		
    }
}

