//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;


using Ares.Cimes.IntelliService.DbTableRow;
using Ares.Cimes.IntelliService.DbTableSchema;

namespace Ares.Cimes.IntelliService.Info
{
    /// <summary>
    /// 人員上下工HIST資料 (Mapping CST_USR_WORKTIME_HIST Table)
    /// </summary>
    [Serializable]
    public partial class CSTUserWorkTimeHistoryInfo : InfoBase 
    {
        private static readonly CSTUserWorkTimeHistoryInfo s_ProxyInfo;
        
        
        
        private CST_USR_WORKTIME_HIST_Row m_StrongTypeRow { get { return (CST_USR_WORKTIME_HIST_Row)GetSchemaRow(); } }

        /// <summary>
        /// Non-Static Proxy Info Get Property
        /// </summary>        
        protected override InfoBase ProxyInfo { get { return s_ProxyInfo; } }

        #region Properties
        /// <summary>
        /// USR_WORKTIME_HIST_SID
        /// </summary>
        protected override DataColumn IDColumn { get { return CST_USR_WORKTIME_HIST.USR_WORKTIME_HIST_SID; } }
        
                /// <summary>
        /// 人員上下工歷史紀錄系統編號 資料型態:NVARCHAR2(100) 是否允許Null:N 
        /// </summary>
        public String USR_WORKTIME_HIST_SID 
        {
            get { return m_StrongTypeRow.USR_WORKTIME_HIST_SID; }
            set { m_StrongTypeRow.USR_WORKTIME_HIST_SID = value; }
        }
        /// <summary>
        /// 人員上下工系統編號 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String USR_WORKTIME_SID 
        {
            get { return m_StrongTypeRow.USR_WORKTIME_SID; }
            set { m_StrongTypeRow.USR_WORKTIME_SID = value; }
        }
        /// <summary>
        /// 工單 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String WorkOrder 
        {
            get { return m_StrongTypeRow.WO; }
            set { m_StrongTypeRow.WO = value; }
        }
        /// <summary>
        /// 線別/機台 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String LINE 
        {
            get { return m_StrongTypeRow.LINE; }
            set { m_StrongTypeRow.LINE = value; }
        }
        /// <summary>
        /// 上工人員 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String WORKUSERID 
        {
            get { return m_StrongTypeRow.WORKUSERID; }
            set { m_StrongTypeRow.WORKUSERID = value; }
        }
        /// <summary>
        /// 工位 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String USR_WORKPALCE 
        {
            get { return m_StrongTypeRow.USR_WORKPALCE; }
            set { m_StrongTypeRow.USR_WORKPALCE = value; }
        }
        /// <summary>
        /// 上工時間 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String StartTime 
        {
            get { return m_StrongTypeRow.STARTTIME; }
            set { m_StrongTypeRow.STARTTIME = value; }
        }
        /// <summary>
        /// 下工時間 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String EndTime 
        {
            get { return m_StrongTypeRow.ENDTIME; }
            set { m_StrongTypeRow.ENDTIME = value; }
        }
        /// <summary>
        /// Comm系统编号 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String COMM_SID 
        {
            get { return m_StrongTypeRow.COMM_SID; }
            set { m_StrongTypeRow.COMM_SID = value; }
        }
        /// <summary>
        /// 執行標記 資料型態:CHAR(1) 是否允許Null:Y 
        /// </summary>
        public String EXECUTEFLAG 
        {
            get { return m_StrongTypeRow.EXECUTEFLAG; }
            set { m_StrongTypeRow.EXECUTEFLAG = value; }
        }
        /// <summary>
        /// 班别日期 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String SHIFTDATE 
        {
            get { return m_StrongTypeRow.SHIFTDATE; }
            set { m_StrongTypeRow.SHIFTDATE = value; }
        }
        /// <summary>
        /// 班別 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String SHIFT 
        {
            get { return m_StrongTypeRow.SHIFT; }
            set { m_StrongTypeRow.SHIFT = value; }
        }
        /// <summary>
        /// 人員除外系統編號 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String USR_EXCEPT_WORKTIME_SID 
        {
            get { return m_StrongTypeRow.USR_EXCEPT_WORKTIME_SID; }
            set { m_StrongTypeRow.USR_EXCEPT_WORKTIME_SID = value; }
        }
        /// <summary>
        ///  資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String Lot 
        {
            get { return m_StrongTypeRow.LOT; }
            set { m_StrongTypeRow.LOT = value; }
        }

                
        /// <summary>
        /// User ID
        /// </summary>
        public override string UserID { get { return m_StrongTypeRow.USERID; } protected set { m_StrongTypeRow.USERID = value; } }
        
        /// <summary>
        /// Update Time
        /// </summary>
        public override string UpdateTime { get { return m_StrongTypeRow.UPDATETIME; } protected set { m_StrongTypeRow.UPDATETIME = value; } }
        #endregion Properties

        #region Ctor(...)
        static CSTUserWorkTimeHistoryInfo()
        {
            CSTUserWorkTimeHistoryInfo info = new CSTUserWorkTimeHistoryInfo();
            info.SetSchemaRow(CST_USR_WORKTIME_HIST.NewRow());
            s_ProxyInfo = info;
        }
        
        /// <summary>
        /// 建構一空的 CSTUserWorkTimeHistoryInfo 物件, 此 Ctor 是供 Generator 使用, 請勿直接呼叫.
        /// </summary>
        public CSTUserWorkTimeHistoryInfo() { }
        
        /// <summary>
        /// 建構一新的 CSTUserWorkTimeHistoryInfo object，由指定的 CST_USR_WORKTIME_HIST_Row 為 Raw Row。
        /// 此 Ctor 只供內部程式呼叫使用, 不為 public ctor.
        /// </summary>
        [Obsolete("已被 InfoBase.Create method 取代")]
        protected internal CSTUserWorkTimeHistoryInfo(CST_USR_WORKTIME_HIST_Row row) : base(row) { }
        #endregion
        
     
		
    }
}

