//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;


using Ares.Cimes.IntelliService.DbTableRow;
using Ares.Cimes.IntelliService.DbTableSchema;

namespace Ares.Cimes.IntelliService.Info
{
    /// <summary>
    ///  (Mapping CST_WMS_MAST_BAK Table)
    /// </summary>
    [Serializable]
    public partial class CSTWMSMastBAKInfo : InfoBase 
    {
        private static readonly CSTWMSMastBAKInfo s_ProxyInfo;
        
        
        
        private CST_WMS_MAST_BAK_Row m_StrongTypeRow { get { return (CST_WMS_MAST_BAK_Row)GetSchemaRow(); } }

        /// <summary>
        /// Non-Static Proxy Info Get Property
        /// </summary>        
        protected override InfoBase ProxyInfo { get { return s_ProxyInfo; } }

        #region Properties
        /// <summary>
        /// #SIDColumnName
        /// </summary>
        protected override DataColumn IDColumn { get { return CST_WMS_MAST_BAK.WMS_MAST_BAK_SID; } }
        
                /// <summary>
        /// 入庫主檔領用紀錄系統編號 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String WMS_MAST_BAK_SID 
        {
            get { return m_StrongTypeRow.WMS_MAST_BAK_SID; }
            set { m_StrongTypeRow.WMS_MAST_BAK_SID = value; }
        }
        /// <summary>
        /// 入庫主檔系統編號 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String WMS_MAST_SID 
        {
            get { return m_StrongTypeRow.WMS_MAST_SID; }
            set { m_StrongTypeRow.WMS_MAST_SID = value; }
        }
        /// <summary>
        /// 入庫批號 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String Lot 
        {
            get { return m_StrongTypeRow.LOT; }
            set { m_StrongTypeRow.LOT = value; }
        }
        /// <summary>
        /// 入庫料號 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String DeviceName 
        {
            get { return m_StrongTypeRow.DEVICE; }
            set { m_StrongTypeRow.DEVICE = value; }
        }
        /// <summary>
        /// 領用批號 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String ReceiveLot 
        {
            get { return m_StrongTypeRow.RECEIVELOT; }
            set { m_StrongTypeRow.RECEIVELOT = value; }
        }
        /// <summary>
        /// 主檔與明細的關聯編號 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String LIKSID 
        {
            get { return m_StrongTypeRow.LIKSID; }
            set { m_StrongTypeRow.LIKSID = value; }
        }

                
        /// <summary>
        /// User ID
        /// </summary>
        public override string UserID { get { return m_StrongTypeRow.USERID; } protected set { m_StrongTypeRow.USERID = value; } }
        
        /// <summary>
        /// Update Time
        /// </summary>
        public override string UpdateTime { get { return m_StrongTypeRow.UPDATETIME; } protected set { m_StrongTypeRow.UPDATETIME = value; } }
        #endregion Properties

        #region Ctor(...)
        static CSTWMSMastBAKInfo()
        {
            CSTWMSMastBAKInfo info = new CSTWMSMastBAKInfo();
            info.SetSchemaRow(CST_WMS_MAST_BAK.NewRow());
            s_ProxyInfo = info;
        }
        
        /// <summary>
        /// 建構一空的 CSTWMSMastBAKInfo 物件, 此 Ctor 是供 Generator 使用, 請勿直接呼叫.
        /// </summary>
        public CSTWMSMastBAKInfo() { }
        
        /// <summary>
        /// 建構一新的 CSTWMSMastBAKInfo object，由指定的 CST_WMS_MAST_BAK_Row 為 Raw Row。
        /// 此 Ctor 只供內部程式呼叫使用, 不為 public ctor.
        /// </summary>
        [Obsolete("已被 InfoBase.Create method 取代")]
        protected internal CSTWMSMastBAKInfo(CST_WMS_MAST_BAK_Row row) : base(row) { }
        #endregion
        
     
		
    }
}

