//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;


using Ares.Cimes.IntelliService.DbTableRow;
using Ares.Cimes.IntelliService.DbTableSchema;

namespace Ares.Cimes.IntelliService.Info
{
    /// <summary>
    ///  (Mapping CST_WPC_WO_LOT Table)
    /// </summary>
    [Serializable]
    public partial class CSTWorkOrderLotInfo : InfoBase 
    {
        private static readonly CSTWorkOrderLotInfo s_ProxyInfo;
        
        
        
        private CST_WPC_WO_LOT_Row m_StrongTypeRow { get { return (CST_WPC_WO_LOT_Row)GetSchemaRow(); } }

        /// <summary>
        /// Non-Static Proxy Info Get Property
        /// </summary>        
        protected override InfoBase ProxyInfo { get { return s_ProxyInfo; } }

        #region Properties
        /// <summary>
        /// WPC_WO_LOT_SID
        /// </summary>
        protected override DataColumn IDColumn { get { return CST_WPC_WO_LOT.WPC_WO_LOT_SID; } }
        
                /// <summary>
        /// 工單批號明細系統編號 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String WPC_WO_LOT_SID 
        {
            get { return m_StrongTypeRow.WPC_WO_LOT_SID; }
            set { m_StrongTypeRow.WPC_WO_LOT_SID = value; }
        }
        /// <summary>
        /// 工單 資料型態:NVARCHAR2(100) 是否允許Null:N 
        /// </summary>
        public String WorkOrder 
        {
            get { return m_StrongTypeRow.WO; }
            set { m_StrongTypeRow.WO = value; }
        }
        /// <summary>
        /// 工單序號 資料型態:NUMBER(38) 是否允許Null:N 
        /// </summary>
        public Decimal WOSEQUENCE 
        {
            get { return m_StrongTypeRow.WOSEQUENCE; }
            set { m_StrongTypeRow.WOSEQUENCE = value; }
        }
        /// <summary>
        /// 工單批 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String WOLOT 
        {
            get { return m_StrongTypeRow.WOLOT; }
            set { m_StrongTypeRow.WOLOT = value; }
        }
        /// <summary>
        /// 入庫批 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String INVLOT 
        {
            get { return m_StrongTypeRow.INVLOT; }
            set { m_StrongTypeRow.INVLOT = value; }
        }
        /// <summary>
        /// 物料批 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String MATERIALLOT 
        {
            get { return m_StrongTypeRow.MATERIALLOT; }
            set { m_StrongTypeRow.MATERIALLOT = value; }
        }
        /// <summary>
        /// 發料數量 資料型態:NUMBER(13) 是否允許Null:Y 
        /// </summary>
        public Decimal Quantity 
        {
            get { return m_StrongTypeRow.QUANTITY; }
            set { m_StrongTypeRow.QUANTITY = value; }
        }
        /// <summary>
        /// 領料狀態 Y:已領料、N:未領料	 資料型態:NVARCHAR2(100) 是否允許Null:N 
        /// </summary>
        public String CreateFlag
        {
            get { return m_StrongTypeRow.CREATEFLAG; }
            set { m_StrongTypeRow.CREATEFLAG = value; }
        }


        #endregion Properties

        #region Ctor(...)
        static CSTWorkOrderLotInfo()
        {
            CSTWorkOrderLotInfo info = new CSTWorkOrderLotInfo();
            info.SetSchemaRow(CST_WPC_WO_LOT.NewRow());
            s_ProxyInfo = info;
        }
        
        /// <summary>
        /// 建構一空的 CSTWorkOrderLotInfo 物件, 此 Ctor 是供 Generator 使用, 請勿直接呼叫.
        /// </summary>
        public CSTWorkOrderLotInfo() { }
        
        /// <summary>
        /// 建構一新的 CSTWorkOrderLotInfo object，由指定的 CST_WPC_WO_LOT_Row 為 Raw Row。
        /// 此 Ctor 只供內部程式呼叫使用, 不為 public ctor.
        /// </summary>
        [Obsolete("已被 InfoBase.Create method 取代")]
        protected internal CSTWorkOrderLotInfo(CST_WPC_WO_LOT_Row row) : base(row) { }
        #endregion
        
     
		
    }
}

