//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;


using Ares.Cimes.IntelliService.DbTableRow;
using Ares.Cimes.IntelliService.DbTableSchema;

namespace Ares.Cimes.IntelliService.Info
{
    /// <summary>
    ///  (Mapping CST_WIP_ASSEMBLY_FILE_LOG Table)
    /// </summary>
    [Serializable]
    public partial class CSTWipAssemblyFileLogInfo : InfoBase 
    {
        private static readonly CSTWipAssemblyFileLogInfo s_ProxyInfo;
        
        
        
        private CST_WIP_ASSEMBLY_FILE_LOG_Row m_StrongTypeRow { get { return (CST_WIP_ASSEMBLY_FILE_LOG_Row)GetSchemaRow(); } }

        /// <summary>
        /// Non-Static Proxy Info Get Property
        /// </summary>        
        protected override InfoBase ProxyInfo { get { return s_ProxyInfo; } }

        #region Properties
        /// <summary>
        /// #SIDColumnName
        /// </summary>
        protected override DataColumn IDColumn { get { return CST_WIP_ASSEMBLY_FILE_LOG.WIP_ASSEMBLY_FILE_LOG_SID; } }
        
                /// <summary>
        /// 裝配檔案紀錄SID 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String WIP_ASSEMBLY_FILE_LOG_SID 
        {
            get { return m_StrongTypeRow.WIP_ASSEMBLY_FILE_LOG_SID; }
            set { m_StrongTypeRow.WIP_ASSEMBLY_FILE_LOG_SID = value; }
        }
        /// <summary>
        /// 裝配檔案紀錄SID 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String WIP_ASSEMBLY_FILE_SID 
        {
            get { return m_StrongTypeRow.WIP_ASSEMBLY_FILE_SID; }
            set { m_StrongTypeRow.WIP_ASSEMBLY_FILE_SID = value; }
        }
        /// <summary>
        /// 機台 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String EquipmentName 
        {
            get { return m_StrongTypeRow.EQUIPMENT; }
            set { m_StrongTypeRow.EQUIPMENT = value; }
        }
        /// <summary>
        /// 機台位置 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String Location 
        {
            get { return m_StrongTypeRow.LOCATION; }
            set { m_StrongTypeRow.LOCATION = value; }
        }
        /// <summary>
        /// 檔案名稱 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String FileName 
        {
            get { return m_StrongTypeRow.FILENAME; }
            set { m_StrongTypeRow.FILENAME = value; }
        }

        /// <summary>
        /// 檔案建立時間 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String FileTime
        {
            get { return m_StrongTypeRow.FILETIME; }
            set { m_StrongTypeRow.FILETIME = value; }
        }


        /// <summary>
        /// Update Time
        /// </summary>
        public override string UpdateTime { get { return m_StrongTypeRow.UPDATETIME; } protected set { m_StrongTypeRow.UPDATETIME = value; } }
        #endregion Properties

        #region Ctor(...)
        static CSTWipAssemblyFileLogInfo()
        {
            CSTWipAssemblyFileLogInfo info = new CSTWipAssemblyFileLogInfo();
            info.SetSchemaRow(CST_WIP_ASSEMBLY_FILE_LOG.NewRow());
            s_ProxyInfo = info;
        }
        
        /// <summary>
        /// 建構一空的 CSTWipAssemblyFileLogInfo 物件, 此 Ctor 是供 Generator 使用, 請勿直接呼叫.
        /// </summary>
        public CSTWipAssemblyFileLogInfo() { }
        
        /// <summary>
        /// 建構一新的 CSTWipAssemblyFileLogInfo object，由指定的 CST_WIP_ASSEMBLY_FILE_LOG_Row 為 Raw Row。
        /// 此 Ctor 只供內部程式呼叫使用, 不為 public ctor.
        /// </summary>
        [Obsolete("已被 InfoBase.Create method 取代")]
        protected internal CSTWipAssemblyFileLogInfo(CST_WIP_ASSEMBLY_FILE_LOG_Row row) : base(row) { }
        #endregion
        
     
		
    }
}

