//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;


using Ares.Cimes.IntelliService.DbTableRow;
using Ares.Cimes.IntelliService.DbTableSchema;

namespace Ares.Cimes.IntelliService.Info
{
    /// <summary>
    ///  (Mapping CST_WIP_CMM Table)
    /// </summary>
    [Serializable]
    public partial class CSTWIPCMMInfo : InfoBase 
    {
        private static readonly CSTWIPCMMInfo s_ProxyInfo;
        
        
        
        private CST_WIP_CMM_Row m_StrongTypeRow { get { return (CST_WIP_CMM_Row)GetSchemaRow(); } }

        /// <summary>
        /// Non-Static Proxy Info Get Property
        /// </summary>        
        protected override InfoBase ProxyInfo { get { return s_ProxyInfo; } }

        #region Properties
        /// <summary>
        /// #SIDColumnName
        /// </summary>
        protected override DataColumn IDColumn { get { return CST_WIP_CMM.WIP_CMM_SID; } }
        
                /// <summary>
        /// 三次元主檔系統編號 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String WIPCMMSID 
        {
            get { return m_StrongTypeRow.WIP_CMM_SID; }
            set { m_StrongTypeRow.WIP_CMM_SID = value; }
        }
        /// <summary>
        /// 加工機台 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String Equipment 
        {
            get { return m_StrongTypeRow.EQUIPMENT; }
            set { m_StrongTypeRow.EQUIPMENT = value; }
        }
        /// <summary>
        /// 產品名稱 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String Device 
        {
            get { return m_StrongTypeRow.DEVICE; }
            set { m_StrongTypeRow.DEVICE = value; }
        }
        /// <summary>
        /// 班別 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String Shift 
        {
            get { return m_StrongTypeRow.SHIFT; }
            set { m_StrongTypeRow.SHIFT = value; }
        }
        /// <summary>
        /// 量測機台 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String MeasureEQP 
        {
            get { return m_StrongTypeRow.MEASUREEQP; }
            set { m_StrongTypeRow.MEASUREEQP = value; }
        }
        /// <summary>
        /// 檢驗員 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String Inspuser 
        {
            get { return m_StrongTypeRow.INSPUSER; }
            set { m_StrongTypeRow.INSPUSER = value; }
        }
        /// <summary>
        /// 工件號或是小工單號 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String FileID 
        {
            get { return m_StrongTypeRow.FILEID; }
            set { m_StrongTypeRow.FILEID = value; }
        }
        /// <summary>
        /// 解析時間 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String Parsetime 
        {
            get { return m_StrongTypeRow.PARSETIME; }
            set { m_StrongTypeRow.PARSETIME = value; }
        }
        /// <summary>
        /// 配對到的檢驗單號 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String QCInspectionSID 
        {
            get { return m_StrongTypeRow.QC_INSP_SID; }
            set { m_StrongTypeRow.QC_INSP_SID = value; }
        }

                
        ///// <summary>
        ///// User ID
        ///// </summary>
        //public override string UserID { get { return m_StrongTypeRow.USERID; } protected set { m_StrongTypeRow.USERID = value; } }
        
        /// <summary>
        /// Update Time
        /// </summary>
        public override string UpdateTime { get { return m_StrongTypeRow.UPDATETIME; } protected set { m_StrongTypeRow.UPDATETIME = value; } }
        #endregion Properties

        #region Ctor(...)
        static CSTWIPCMMInfo()
        {
            CSTWIPCMMInfo info = new CSTWIPCMMInfo();
            info.SetSchemaRow(CST_WIP_CMM.NewRow());
            s_ProxyInfo = info;
        }
        
        /// <summary>
        /// 建構一空的 CSTWIPCMMInfo 物件, 此 Ctor 是供 Generator 使用, 請勿直接呼叫.
        /// </summary>
        public CSTWIPCMMInfo() { }
        
        /// <summary>
        /// 建構一新的 CSTWIPCMMInfo object，由指定的 CST_WIP_CMM_Row 為 Raw Row。
        /// 此 Ctor 只供內部程式呼叫使用, 不為 public ctor.
        /// </summary>
        [Obsolete("已被 InfoBase.Create method 取代")]
        protected internal CSTWIPCMMInfo(CST_WIP_CMM_Row row) : base(row) { }
        #endregion
        
     
		
    }
}

