//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;


using Ares.Cimes.IntelliService.DbTableRow;
using Ares.Cimes.IntelliService.DbTableSchema;

namespace Ares.Cimes.IntelliService.Info
{
    /// <summary>
    ///  (Mapping CST_WIP_CMM_DATA Table)
    /// </summary>
    [Serializable]
    public partial class CSTWIPCMMDataInfo : InfoBase 
    {
        private static readonly CSTWIPCMMDataInfo s_ProxyInfo;
        
        
        
        private CST_WIP_CMM_DATA_Row m_StrongTypeRow { get { return (CST_WIP_CMM_DATA_Row)GetSchemaRow(); } }

        /// <summary>
        /// Non-Static Proxy Info Get Property
        /// </summary>        
        protected override InfoBase ProxyInfo { get { return s_ProxyInfo; } }

        #region Properties
        /// <summary>
        /// #SIDColumnName
        /// </summary>
        protected override DataColumn IDColumn { get { return CST_WIP_CMM_DATA.WIP_CMM_DATA_SID; } }
        
                /// <summary>
        /// 三次元資料系統編號 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String WIPCMMDataSID 
        {
            get { return m_StrongTypeRow.WIP_CMM_DATA_SID; }
            set { m_StrongTypeRow.WIP_CMM_DATA_SID = value; }
        }
        /// <summary>
        /// 三次元主檔系統編號 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String WIPCMMSID 
        {
            get { return m_StrongTypeRow.WIP_CMM_SID; }
            set { m_StrongTypeRow.WIP_CMM_SID = value; }
        }
        /// <summary>
        /// 特性參數 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String Characteristic 
        {
            get { return m_StrongTypeRow.CHARACTERISTIC; }
            set { m_StrongTypeRow.CHARACTERISTIC = value; }
        }
        /// <summary>
        /// 實際值 資料型態:NUMBER(20) 是否允許Null:Y 
        /// </summary>
        public Decimal Actual 
        {
            get { return m_StrongTypeRow.ACTUAL; }
            set { m_StrongTypeRow.ACTUAL = value; }
        }
        /// <summary>
        /// 參考值 資料型態:NUMBER(20) 是否允許Null:Y 
        /// </summary>
        public Decimal Nominal 
        {
            get { return m_StrongTypeRow.NOMINAL; }
            set { m_StrongTypeRow.NOMINAL = value; }
        }
        /// <summary>
        /// 上限值 資料型態:NUMBER(20) 是否允許Null:Y 
        /// </summary>
        public Decimal Upper 
        {
            get { return m_StrongTypeRow.UPPERTOL; }
            set { m_StrongTypeRow.UPPERTOL = value; }
        }
        /// <summary>
        /// 下限值 資料型態:NUMBER(20) 是否允許Null:Y 
        /// </summary>
        public Decimal Lower 
        {
            get { return m_StrongTypeRow.LOWERTOL; }
            set { m_StrongTypeRow.LOWERTOL = value; }
        }
        /// <summary>
        /// 標準差 資料型態:NUMBER(20) 是否允許Null:Y 
        /// </summary>
        public Decimal Deviation 
        {
            get { return m_StrongTypeRow.DEVIATION; }
            set { m_StrongTypeRow.DEVIATION = value; }
        }

                
        ///// <summary>
        ///// User ID
        ///// </summary>
        //public override string UserID { get { return m_StrongTypeRow.USERID; } protected set { m_StrongTypeRow.USERID = value; } }
        
        ///// <summary>
        ///// Update Time
        ///// </summary>
        //public override string UpdateTime { get { return m_StrongTypeRow.UPDATETIME; } protected set { m_StrongTypeRow.UPDATETIME = value; } }
        #endregion Properties

        #region Ctor(...)
        static CSTWIPCMMDataInfo()
        {
            CSTWIPCMMDataInfo info = new CSTWIPCMMDataInfo();
            info.SetSchemaRow(CST_WIP_CMM_DATA.NewRow());
            s_ProxyInfo = info;
        }
        
        /// <summary>
        /// 建構一空的 CSTWIPCMMDataInfo 物件, 此 Ctor 是供 Generator 使用, 請勿直接呼叫.
        /// </summary>
        public CSTWIPCMMDataInfo() { }
        
        /// <summary>
        /// 建構一新的 CSTWIPCMMDataInfo object，由指定的 CST_WIP_CMM_DATA_Row 為 Raw Row。
        /// 此 Ctor 只供內部程式呼叫使用, 不為 public ctor.
        /// </summary>
        [Obsolete("已被 InfoBase.Create method 取代")]
        protected internal CSTWIPCMMDataInfo(CST_WIP_CMM_DATA_Row row) : base(row) { }
        #endregion
        
     
		
    }
}

