//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;


using Ares.Cimes.IntelliService.DbTableRow;
using Ares.Cimes.IntelliService.DbTableSchema;

namespace Ares.Cimes.IntelliService.Info
{
    /// <summary>
    ///  (Mapping CST_WIP_PPK Table)
    /// </summary>
    [Serializable]
    public partial class CSTWipPPKInfo : InfoBase 
    {
        private static readonly CSTWipPPKInfo s_ProxyInfo;
        
        
        
        private CST_WIP_PPK_Row m_StrongTypeRow { get { return (CST_WIP_PPK_Row)GetSchemaRow(); } }

        /// <summary>
        /// Non-Static Proxy Info Get Property
        /// </summary>        
        protected override InfoBase ProxyInfo { get { return s_ProxyInfo; } }

        #region Properties
        /// <summary>
        /// #SIDColumnName
        /// </summary>
        protected override DataColumn IDColumn { get { return CST_WIP_PPK.WIP_PPK_SID; } }
        
                /// <summary>
        /// PPK資訊系統編號 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String WIP_PPK_SID 
        {
            get { return m_StrongTypeRow.WIP_PPK_SID; }
            set { m_StrongTypeRow.WIP_PPK_SID = value; }
        }
        /// <summary>
        /// 機台 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String EquipmentName 
        {
            get { return m_StrongTypeRow.EQP; }
            set { m_StrongTypeRow.EQP = value; }
        }
        /// <summary>
        /// 料號 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String DeviceName 
        {
            get { return m_StrongTypeRow.DEVICE; }
            set { m_StrongTypeRow.DEVICE = value; }
        }
        /// <summary>
        /// 狀態 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String Status 
        {
            get { return m_StrongTypeRow.STATUS; }
            set { m_StrongTypeRow.STATUS = value; }
        }
        /// <summary>
        /// PPK送驗支數 資料型態:NUMBER() 是否允許Null:Y 
        /// </summary>
        public Decimal PPKCOUNT 
        {
            get { return m_StrongTypeRow.PPKCOUNT; }
            set { m_StrongTypeRow.PPKCOUNT = value; }
        }

                
        
        #endregion Properties

        #region Ctor(...)
        static CSTWipPPKInfo()
        {
            CSTWipPPKInfo info = new CSTWipPPKInfo();
            info.SetSchemaRow(CST_WIP_PPK.NewRow());
            s_ProxyInfo = info;
        }
        
        /// <summary>
        /// 建構一空的 CSTWipPPKInfo 物件, 此 Ctor 是供 Generator 使用, 請勿直接呼叫.
        /// </summary>
        public CSTWipPPKInfo() { }
        
        /// <summary>
        /// 建構一新的 CSTWipPPKInfo object，由指定的 CST_WIP_PPK_Row 為 Raw Row。
        /// 此 Ctor 只供內部程式呼叫使用, 不為 public ctor.
        /// </summary>
        [Obsolete("已被 InfoBase.Create method 取代")]
        protected internal CSTWipPPKInfo(CST_WIP_PPK_Row row) : base(row) { }
        #endregion
        
     
		
    }
}

