//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;


using Ares.Cimes.IntelliService.DbTableRow;
using Ares.Cimes.IntelliService.DbTableSchema;

namespace Ares.Cimes.IntelliService.Info
{
    /// <summary>
    ///  (Mapping CST_WIP_DEFECT_JUDGEMENT Table)
    /// </summary>
    [Serializable]
    public partial class CSTWIPDefectJudgementInfo : InfoBase 
    {
        private static readonly CSTWIPDefectJudgementInfo s_ProxyInfo;
        
        
        
        private CST_WIP_DEFECT_JUDGEMENT_Row m_StrongTypeRow { get { return (CST_WIP_DEFECT_JUDGEMENT_Row)GetSchemaRow(); } }

        /// <summary>
        /// Non-Static Proxy Info Get Property
        /// </summary>        
        protected override InfoBase ProxyInfo { get { return s_ProxyInfo; } }

        #region Properties
        /// <summary>
        /// #SIDColumnName
        /// </summary>
        protected override DataColumn IDColumn { get { return CST_WIP_DEFECT_JUDGEMENT.WIP_DEFECT_JUDGEMENT_SID; } }
        
                /// <summary>
        /// 不良判定結果系統編號 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String WIPDefectJudgementSID 
        {
            get { return m_StrongTypeRow.WIP_DEFECT_JUDGEMENT_SID; }
            set { m_StrongTypeRow.WIP_DEFECT_JUDGEMENT_SID = value; }
        }
        /// <summary>
        /// 不良原因系統編號 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String WIPDefectSID 
        {
            get { return m_StrongTypeRow.WIP_DEFECT_SID; }
            set { m_StrongTypeRow.WIP_DEFECT_SID = value; }
        }
        /// <summary>
        /// 判定結果：良品(Goods)、維修(Repair)、不良品入庫(DefectInv)、報廢入庫(ScrapInv) 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String Result 
        {
            get { return m_StrongTypeRow.RESULT; }
            set { m_StrongTypeRow.RESULT = value; }
        }
        /// <summary>
        /// 判定原因 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String Reason 
        {
            get { return m_StrongTypeRow.REASON; }
            set { m_StrongTypeRow.REASON = value; }
        }
        /// <summary>
        /// 判定說明 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String Description 
        {
            get { return m_StrongTypeRow.DESCRIPTION; }
            set { m_StrongTypeRow.DESCRIPTION = value; }
        }
        /// <summary>
        /// 批號歷史紀錄LINKSID 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String LinkSID 
        {
            get { return m_StrongTypeRow.LINKSID; }
            set { m_StrongTypeRow.LINKSID = value; }
        }

                
        /// <summary>
        /// User ID
        /// </summary>
        public override string UserID { get { return m_StrongTypeRow.USERID; } protected set { m_StrongTypeRow.USERID = value; } }
        
        /// <summary>
        /// Update Time
        /// </summary>
        public override string UpdateTime { get { return m_StrongTypeRow.UPDATETIME; } protected set { m_StrongTypeRow.UPDATETIME = value; } }
        #endregion Properties

        #region Ctor(...)
        static CSTWIPDefectJudgementInfo()
        {
            CSTWIPDefectJudgementInfo info = new CSTWIPDefectJudgementInfo();
            info.SetSchemaRow(CST_WIP_DEFECT_JUDGEMENT.NewRow());
            s_ProxyInfo = info;
        }
        
        /// <summary>
        /// 建構一空的 CSTWIPDefectJudgementInfo 物件, 此 Ctor 是供 Generator 使用, 請勿直接呼叫.
        /// </summary>
        public CSTWIPDefectJudgementInfo() { }
        
        /// <summary>
        /// 建構一新的 CSTWIPDefectJudgementInfo object，由指定的 CST_WIP_DEFECT_JUDGEMENT_Row 為 Raw Row。
        /// 此 Ctor 只供內部程式呼叫使用, 不為 public ctor.
        /// </summary>
        [Obsolete("已被 InfoBase.Create method 取代")]
        protected internal CSTWIPDefectJudgementInfo(CST_WIP_DEFECT_JUDGEMENT_Row row) : base(row) { }
        #endregion
        
     
		
    }
}

