//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;


using Ares.Cimes.IntelliService.DbTableRow;
using Ares.Cimes.IntelliService.DbTableSchema;

namespace Ares.Cimes.IntelliService.Info
{
    /// <summary>
    /// FQC不良紀錄 (Mapping CST_WIP_FQC_DEFECT Table)
    /// </summary>
    [Serializable]
    public partial class CSTWipFQCDefectInfo : InfoBase 
    {
        private static readonly CSTWipFQCDefectInfo s_ProxyInfo;
        
        
        
        private CST_WIP_FQC_DEFECT_Row m_StrongTypeRow { get { return (CST_WIP_FQC_DEFECT_Row)GetSchemaRow(); } }

        /// <summary>
        /// Non-Static Proxy Info Get Property
        /// </summary>        
        protected override InfoBase ProxyInfo { get { return s_ProxyInfo; } }

        #region Properties
        /// <summary>
        /// WIP_FQC_DEFECT_SID
        /// </summary>
        protected override DataColumn IDColumn { get { return CST_WIP_FQC_DEFECT.WIP_FQC_DEFECT_SID; } }
        
                /// <summary>
        /// FQC不良紀錄系統編號 資料型態:NVARCHAR2(100) 是否允許Null:N 
        /// </summary>
        public String WIP_FQC_DEFECT_SID 
        {
            get { return m_StrongTypeRow.WIP_FQC_DEFECT_SID; }
            set { m_StrongTypeRow.WIP_FQC_DEFECT_SID = value; }
        }
        /// <summary>
        /// 箱號 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String BOXNO 
        {
            get { return m_StrongTypeRow.BOXNO; }
            set { m_StrongTypeRow.BOXNO = value; }
        }
        /// <summary>
        /// 工件號 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String ComponentID 
        {
            get { return m_StrongTypeRow.COMPONENTID; }
            set { m_StrongTypeRow.COMPONENTID = value; }
        }
        /// <summary>
        /// 不良原因 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String Reason 
        {
            get { return m_StrongTypeRow.REASON; }
            set { m_StrongTypeRow.REASON = value; }
        }
        /// <summary>
        /// 不良部位 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String PARTS 
        {
            get { return m_StrongTypeRow.PARTS; }
            set { m_StrongTypeRow.PARTS = value; }
        }
        /// <summary>
        /// 一次交易的關聯SID 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String LinkSID 
        {
            get { return m_StrongTypeRow.LINKSID; }
            set { m_StrongTypeRow.LINKSID = value; }
        }


        /// <summary>
        /// User ID
        /// </summary>
        public override string UserID { get { return m_StrongTypeRow.USERID; } protected set { m_StrongTypeRow.USERID = value; } }

        /// <summary>
        /// Update Time
        /// </summary>
        public override string UpdateTime { get { return m_StrongTypeRow.UPDATETIME; } protected set { m_StrongTypeRow.UPDATETIME = value; } }
        #endregion Properties

        #region Ctor(...)
        static CSTWipFQCDefectInfo()
        {
            CSTWipFQCDefectInfo info = new CSTWipFQCDefectInfo();
            info.SetSchemaRow(CST_WIP_FQC_DEFECT.NewRow());
            s_ProxyInfo = info;
        }
        
        /// <summary>
        /// 建構一空的 CSTWipFQCDefectInfo 物件, 此 Ctor 是供 Generator 使用, 請勿直接呼叫.
        /// </summary>
        public CSTWipFQCDefectInfo() { }
        
        /// <summary>
        /// 建構一新的 CSTWipFQCDefectInfo object，由指定的 CST_WIP_FQC_DEFECT_Row 為 Raw Row。
        /// 此 Ctor 只供內部程式呼叫使用, 不為 public ctor.
        /// </summary>
        [Obsolete("已被 InfoBase.Create method 取代")]
        protected internal CSTWipFQCDefectInfo(CST_WIP_FQC_DEFECT_Row row) : base(row) { }
        #endregion
        
     
		
    }
}

