//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;
using System.Runtime.Serialization;
using System.Text;

using Ares.Cimes.IntelliService.DbTableSchema;

namespace Ares.Cimes.IntelliService.DbTableRow
{
    /// <summary>
    /// CST_PRC_OPER_MAPPING_Row, ERP與MES站點對應主檔
    /// </summary>
    [Serializable]
    public class CST_PRC_OPER_MAPPING_Row : DBTableRowBase
    {            
        /// <summary>
        /// 取得該 Row 是屬於 CST_PRC_OPER_MAPPING Table, 傳回代表該 Table Schema 的唯一實體
        /// </summary>
        public override DBTableSchemaBase TableSchema
        {
            get { return CST_PRC_OPER_MAPPING.Singleton; }
        }
    
        #region Ctor()
        /// <summary>
        /// 建構一個空的 CST_PRC_OPER_MAPPING_Row 物件.
        /// 此 Ctor 僅供 Cimes 內部 Generator 使用, 若要取得一 Row 實體, 請使用 Schema.NewRow()
        /// </summary>
        public CST_PRC_OPER_MAPPING_Row() : base() {  }

        /// <summary>
        /// 以原生 DataRow 建構一個 CST_PRC_OPER_MAPPING_Row 物件
        /// </summary>
        /// <param name="row">原生 DataRow</param>
        public CST_PRC_OPER_MAPPING_Row(DataRow row) : base(row) {  }
        
        /// <summary>
        /// For Serializable Operation
        /// </summary>
        /// <param name="si">SerializationInfo</param>
        /// <param name="context">StreamingContext</param>
        protected CST_PRC_OPER_MAPPING_Row(SerializationInfo si, StreamingContext context) : base(si, context) {  }
        #endregion

                    /// <summary>
    /// ERP與MES站點對應主檔SID 資料型態:NVARCHAR2(100) 是否允許Null:N 
    /// </summary>
    public String PRC_OPER_MAPPING_SID { 
      get { return (this["PRC_OPER_MAPPING_SID"] is DBNull) ? string.Empty : (String) this["PRC_OPER_MAPPING_SID"]; } 
      set { this["PRC_OPER_MAPPING_SID"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// ERP站點 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String ERPOPER { 
      get { return (this["ERPOPER"] is DBNull) ? string.Empty : (String) this["ERPOPER"]; } 
      set { this["ERPOPER"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 說明 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String DESCR { 
      get { return (this["DESCR"] is DBNull) ? string.Empty : (String) this["DESCR"]; } 
      set { this["DESCR"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 啟用狀態 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String STATUS { 
      get { return (this["STATUS"] is DBNull) ? string.Empty : (String) this["STATUS"]; } 
      set { this["STATUS"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 是否啟用 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String ACTIVEFLAG { 
      get { return (this["ACTIVEFLAG"] is DBNull) ? string.Empty : (String) this["ACTIVEFLAG"]; } 
      set { this["ACTIVEFLAG"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 系統用來控制修改前後資訊一致的參數 資料型態:NUMBER(38) 是否允許Null:Y 
    /// </summary>
    public Decimal TAG { 
      get { return (this["TAG"] is DBNull) ? 0 : decimal.Parse(this["TAG"].ToString()).FormatDecimal(); } 
      set { this["TAG"] = value; } 
    } 

    /// <summary>
    /// 使用者 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String USERID { 
      get { return (this["USERID"] is DBNull) ? string.Empty : (String) this["USERID"]; } 
      set { this["USERID"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 更新時間 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String UPDATETIME { 
      get { return (this["UPDATETIME"] is DBNull) ? string.Empty : (String) this["UPDATETIME"]; } 
      set { this["UPDATETIME"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 


        
        /// <summary>
        /// 取得該 Row 的深層複製實體
        /// </summary>              
        /// <returns>深層複製實體</returns>
        public new CST_PRC_OPER_MAPPING_Row DeepCopy()
        {
            return (CST_PRC_OPER_MAPPING_Row) base.DeepCopy();
        }
    }
}


