//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;
using System.Runtime.Serialization;
using System.Text;

using Ares.Cimes.IntelliService.DbTableSchema;

namespace Ares.Cimes.IntelliService.DbTableRow
{
    /// <summary>
    /// CST_PRC_OPER_MAPPING_DATA_Row, ERP與MES站點對應明細
    /// </summary>
    [Serializable]
    public class CST_PRC_OPER_MAPPING_DATA_Row : DBTableRowBase
    {            
        /// <summary>
        /// 取得該 Row 是屬於 CST_PRC_OPER_MAPPING_DATA Table, 傳回代表該 Table Schema 的唯一實體
        /// </summary>
        public override DBTableSchemaBase TableSchema
        {
            get { return CST_PRC_OPER_MAPPING_DATA.Singleton; }
        }
    
        #region Ctor()
        /// <summary>
        /// 建構一個空的 CST_PRC_OPER_MAPPING_DATA_Row 物件.
        /// 此 Ctor 僅供 Cimes 內部 Generator 使用, 若要取得一 Row 實體, 請使用 Schema.NewRow()
        /// </summary>
        public CST_PRC_OPER_MAPPING_DATA_Row() : base() {  }

        /// <summary>
        /// 以原生 DataRow 建構一個 CST_PRC_OPER_MAPPING_DATA_Row 物件
        /// </summary>
        /// <param name="row">原生 DataRow</param>
        public CST_PRC_OPER_MAPPING_DATA_Row(DataRow row) : base(row) {  }
        
        /// <summary>
        /// For Serializable Operation
        /// </summary>
        /// <param name="si">SerializationInfo</param>
        /// <param name="context">StreamingContext</param>
        protected CST_PRC_OPER_MAPPING_DATA_Row(SerializationInfo si, StreamingContext context) : base(si, context) {  }
        #endregion

                    /// <summary>
    /// ERP與MES站點對應明細SID 資料型態:NVARCHAR2(100) 是否允許Null:N 
    /// </summary>
    public String PRC_OPER_MAPPING_DATA_SID { 
      get { return (this["PRC_OPER_MAPPING_DATA_SID"] is DBNull) ? string.Empty : (String) this["PRC_OPER_MAPPING_DATA_SID"]; } 
      set { this["PRC_OPER_MAPPING_DATA_SID"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// ERP與MES站點對應主檔SID 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String PRC_OPER_MAPPING_SID { 
      get { return (this["PRC_OPER_MAPPING_SID"] is DBNull) ? string.Empty : (String) this["PRC_OPER_MAPPING_SID"]; } 
      set { this["PRC_OPER_MAPPING_SID"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 站點順序 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String OPERSEQ { 
      get { return (this["OPERSEQ"] is DBNull) ? string.Empty : (String) this["OPERSEQ"]; } 
      set { this["OPERSEQ"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// MES站點名稱 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String MESOPER { 
      get { return (this["MESOPER"] is DBNull) ? string.Empty : (String) this["MESOPER"]; } 
      set { this["MESOPER"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 說明 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String OPERDESCR { 
      get { return (this["OPERDESCR"] is DBNull) ? string.Empty : (String) this["OPERDESCR"]; } 
      set { this["OPERDESCR"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    }
    /// <summary>
    /// 流程客製站點 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String CUSTPATH
    {
    get { return (this["CUSTPATH"] is DBNull) ? string.Empty : (String)this["CUSTPATH"]; }
    set { this["CUSTPATH"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object)value; }
    }

    /// <summary>
    /// 系統用來控制修改前後資訊一致的參數 資料型態:NUMBER() 是否允許Null:Y 
    /// </summary>
    public Decimal TAG { 
      get { return (this["TAG"] is DBNull) ? 0 : decimal.Parse(this["TAG"].ToString()).FormatDecimal(); } 
      set { this["TAG"] = value; } 
    } 

    /// <summary>
    /// 使用者 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String USERID { 
      get { return (this["USERID"] is DBNull) ? string.Empty : (String) this["USERID"]; } 
      set { this["USERID"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 更新時間 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String UPDATETIME { 
      get { return (this["UPDATETIME"] is DBNull) ? string.Empty : (String) this["UPDATETIME"]; } 
      set { this["UPDATETIME"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 


        
        /// <summary>
        /// 取得該 Row 的深層複製實體
        /// </summary>              
        /// <returns>深層複製實體</returns>
        public new CST_PRC_OPER_MAPPING_DATA_Row DeepCopy()
        {
            return (CST_PRC_OPER_MAPPING_DATA_Row) base.DeepCopy();
        }
    }
}


