//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;
using System.Runtime.Serialization;
using System.Text;

using Ares.Cimes.IntelliService.DbTableSchema;

namespace Ares.Cimes.IntelliService.DbTableRow
{
    /// <summary>
    /// CST_EQP_SETUP_Row, 紀錄機台調機資訊
    /// </summary>
    [Serializable]
    public class CST_EQP_SETUP_Row : DBTableRowBase
    {            
        /// <summary>
        /// 取得該 Row 是屬於 CST_EQP_SETUP Table, 傳回代表該 Table Schema 的唯一實體
        /// </summary>
        public override DBTableSchemaBase TableSchema
        {
            get { return CST_EQP_SETUP.Singleton; }
        }
    
        #region Ctor()
        /// <summary>
        /// 建構一個空的 CST_EQP_SETUP_Row 物件.
        /// 此 Ctor 僅供 Cimes 內部 Generator 使用, 若要取得一 Row 實體, 請使用 Schema.NewRow()
        /// </summary>
        public CST_EQP_SETUP_Row() : base() {  }

        /// <summary>
        /// 以原生 DataRow 建構一個 CST_EQP_SETUP_Row 物件
        /// </summary>
        /// <param name="row">原生 DataRow</param>
        public CST_EQP_SETUP_Row(DataRow row) : base(row) {  }
        
        /// <summary>
        /// For Serializable Operation
        /// </summary>
        /// <param name="si">SerializationInfo</param>
        /// <param name="context">StreamingContext</param>
        protected CST_EQP_SETUP_Row(SerializationInfo si, StreamingContext context) : base(si, context) {  }
        #endregion

                    /// <summary>
    /// 機台調機SID 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String EQP_SETUP_SID { 
      get { return (this["EQP_SETUP_SID"] is DBNull) ? string.Empty : (String) this["EQP_SETUP_SID"]; } 
      set { this["EQP_SETUP_SID"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 機台 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String EQUIPMENT { 
      get { return (this["EQUIPMENT"] is DBNull) ? string.Empty : (String) this["EQUIPMENT"]; } 
      set { this["EQUIPMENT"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 調機原因 資料型態:NVARCHAR2(98) 是否允許Null:Y 
    /// </summary>
    public String REASON { 
      get { return (this["REASON"] is DBNull) ? string.Empty : (String) this["REASON"]; } 
      set { this["REASON"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 調機說明 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String DESCR { 
      get { return (this["DESCR"] is DBNull) ? string.Empty : (String) this["DESCR"]; } 
      set { this["DESCR"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 調機開始時間 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String STARTTIME { 
      get { return (this["STARTTIME"] is DBNull) ? string.Empty : (String) this["STARTTIME"]; } 
      set { this["STARTTIME"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 調機結束時間 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String ENDTIME { 
      get { return (this["ENDTIME"] is DBNull) ? string.Empty : (String) this["ENDTIME"]; } 
      set { this["ENDTIME"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 調機開始人員 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String STARTUSER { 
      get { return (this["STARTUSER"] is DBNull) ? string.Empty : (String) this["STARTUSER"]; } 
      set { this["STARTUSER"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 調機結束人員 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String ENDUSER { 
      get { return (this["ENDUSER"] is DBNull) ? string.Empty : (String) this["ENDUSER"]; } 
      set { this["ENDUSER"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    ///  資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String USERID { 
      get { return (this["USERID"] is DBNull) ? string.Empty : (String) this["USERID"]; } 
      set { this["USERID"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    ///  資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String UPDATETIME { 
      get { return (this["UPDATETIME"] is DBNull) ? string.Empty : (String) this["UPDATETIME"]; } 
      set { this["UPDATETIME"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 


        
        /// <summary>
        /// 取得該 Row 的深層複製實體
        /// </summary>              
        /// <returns>深層複製實體</returns>
        public new CST_EQP_SETUP_Row DeepCopy()
        {
            return (CST_EQP_SETUP_Row) base.DeepCopy();
        }
    }
}


