//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;
using System.Runtime.Serialization;
using System.Text;

using Ares.Cimes.IntelliService.DbTableSchema;

namespace Ares.Cimes.IntelliService.DbTableRow
{
    /// <summary>
    /// CST_USR_EXCEPT_WORKTIME_Row, 
    /// </summary>
    [Serializable]
    public class CST_USR_EXCEPT_WORKTIME_Row : DBTableRowBase
    {            
        /// <summary>
        /// 取得該 Row 是屬於 CST_USR_EXCEPT_WORKTIME Table, 傳回代表該 Table Schema 的唯一實體
        /// </summary>
        public override DBTableSchemaBase TableSchema
        {
            get { return CST_USR_EXCEPT_WORKTIME.Singleton; }
        }
    
        #region Ctor()
        /// <summary>
        /// 建構一個空的 CST_USR_EXCEPT_WORKTIME_Row 物件.
        /// 此 Ctor 僅供 Cimes 內部 Generator 使用, 若要取得一 Row 實體, 請使用 Schema.NewRow()
        /// </summary>
        public CST_USR_EXCEPT_WORKTIME_Row() : base() {  }

        /// <summary>
        /// 以原生 DataRow 建構一個 CST_USR_EXCEPT_WORKTIME_Row 物件
        /// </summary>
        /// <param name="row">原生 DataRow</param>
        public CST_USR_EXCEPT_WORKTIME_Row(DataRow row) : base(row) {  }
        
        /// <summary>
        /// For Serializable Operation
        /// </summary>
        /// <param name="si">SerializationInfo</param>
        /// <param name="context">StreamingContext</param>
        protected CST_USR_EXCEPT_WORKTIME_Row(SerializationInfo si, StreamingContext context) : base(si, context) {  }
        #endregion

                    /// <summary>
    /// 人员除外工时系统编号 資料型態:NVARCHAR2(100) 是否允許Null:N 
    /// </summary>
    public String USR_EXCEPT_WORKTIME_SID { 
      get { return (this["USR_EXCEPT_WORKTIME_SID"] is DBNull) ? string.Empty : (String) this["USR_EXCEPT_WORKTIME_SID"]; } 
      set { this["USR_EXCEPT_WORKTIME_SID"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 除外人员 資料型態:NVARCHAR2(100) 是否允許Null:N 
    /// </summary>
    public String WORK_USERID { 
      get { return (this["WORK_USERID"] is DBNull) ? string.Empty : (String) this["WORK_USERID"]; } 
      set { this["WORK_USERID"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 工作線別 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String WORK_LINE { 
      get { return (this["WORK_LINE"] is DBNull) ? string.Empty : (String) this["WORK_LINE"]; } 
      set { this["WORK_LINE"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 除外原因 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String REASON { 
      get { return (this["REASON"] is DBNull) ? string.Empty : (String) this["REASON"]; } 
      set { this["REASON"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 備註 資料型態:NVARCHAR2(2000) 是否允許Null:Y 
    /// </summary>
    public String REMARK { 
      get { return (this["REMARK"] is DBNull) ? string.Empty : (String) this["REMARK"]; } 
      set { this["REMARK"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 开始时间 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String STARTTIME { 
      get { return (this["STARTTIME"] is DBNull) ? string.Empty : (String) this["STARTTIME"]; } 
      set { this["STARTTIME"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 结束时间 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String ENDTIME { 
      get { return (this["ENDTIME"] is DBNull) ? string.Empty : (String) this["ENDTIME"]; } 
      set { this["ENDTIME"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 


        
        /// <summary>
        /// 取得該 Row 的深層複製實體
        /// </summary>              
        /// <returns>深層複製實體</returns>
        public new CST_USR_EXCEPT_WORKTIME_Row DeepCopy()
        {
            return (CST_USR_EXCEPT_WORKTIME_Row) base.DeepCopy();
        }
    }
}


