//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;
using System.Runtime.Serialization;
using System.Text;

using Ares.Cimes.IntelliService.DbTableSchema;

namespace Ares.Cimes.IntelliService.DbTableRow
{
    /// <summary>
    /// CST_MMS_IQC_INFO_Row, 
    /// </summary>
    [Serializable]
    public class CST_MMS_IQC_INFO_Row : DBTableRowBase
    {            
        /// <summary>
        /// 取得該 Row 是屬於 CST_MMS_IQC_INFO Table, 傳回代表該 Table Schema 的唯一實體
        /// </summary>
        public override DBTableSchemaBase TableSchema
        {
            get { return CST_MMS_IQC_INFO.Singleton; }
        }
    
        #region Ctor()
        /// <summary>
        /// 建構一個空的 CST_MMS_IQC_INFO_Row 物件.
        /// 此 Ctor 僅供 Cimes 內部 Generator 使用, 若要取得一 Row 實體, 請使用 Schema.NewRow()
        /// </summary>
        public CST_MMS_IQC_INFO_Row() : base() {  }

        /// <summary>
        /// 以原生 DataRow 建構一個 CST_MMS_IQC_INFO_Row 物件
        /// </summary>
        /// <param name="row">原生 DataRow</param>
        public CST_MMS_IQC_INFO_Row(DataRow row) : base(row) {  }
        
        /// <summary>
        /// For Serializable Operation
        /// </summary>
        /// <param name="si">SerializationInfo</param>
        /// <param name="context">StreamingContext</param>
        protected CST_MMS_IQC_INFO_Row(SerializationInfo si, StreamingContext context) : base(si, context) {  }
        #endregion

                    /// <summary>
    /// IQC資訊系統編號 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String MMS_IQC_INFO_SID { 
      get { return (this["MMS_IQC_INFO_SID"] is DBNull) ? string.Empty : (String) this["MMS_IQC_INFO_SID"]; } 
      set { this["MMS_IQC_INFO_SID"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 來料爐號 資料型態:NVARCHAR2(100) 是否允許Null:N 
    /// </summary>
    public String RUNID { 
      get { return (this["RUNID"] is DBNull) ? string.Empty : (String) this["RUNID"]; } 
      set { this["RUNID"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 來料批號 資料型態:NVARCHAR2(100) 是否允許Null:N 
    /// </summary>
    public String LOT { 
      get { return (this["LOT"] is DBNull) ? string.Empty : (String) this["LOT"]; } 
      set { this["LOT"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 入廠日期 資料型態:NVARCHAR2(100) 是否允許Null:N 
    /// </summary>
    public String IQCTIME { 
      get { return (this["IQCTIME"] is DBNull) ? string.Empty : (String) this["IQCTIME"]; } 
      set { this["IQCTIME"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 來料數量 資料型態:NUMBER(13) 是否允許Null:Y 
    /// </summary>
    public Decimal QUANTITY { 
      get { return (this["QUANTITY"] is DBNull) ? 0 : decimal.Parse(this["QUANTITY"].ToString()).FormatDecimal(); } 
      set { this["QUANTITY"] = value; } 
    } 
    
    /// <summary>
    /// 物料號 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String MATERIALNO { 
      get { return (this["MATERIALNO"] is DBNull) ? string.Empty : (String) this["MATERIALNO"]; } 
      set { this["MATERIALNO"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 


        
        /// <summary>
        /// 取得該 Row 的深層複製實體
        /// </summary>              
        /// <returns>深層複製實體</returns>
        public new CST_MMS_IQC_INFO_Row DeepCopy()
        {
            return (CST_MMS_IQC_INFO_Row) base.DeepCopy();
        }
    }
}


