//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;
using System.Runtime.Serialization;
using System.Text;

using Ares.Cimes.IntelliService.DbTableSchema;

namespace Ares.Cimes.IntelliService.DbTableRow
{
    /// <summary>
    /// CST_SYS_LOADER_LOG_Row, LOADER的解析紀錄表
    /// </summary>
    [Serializable]
    public class CST_SYS_LOADER_LOG_Row : DBTableRowBase
    {            
        /// <summary>
        /// 取得該 Row 是屬於 CST_SYS_LOADER_LOG Table, 傳回代表該 Table Schema 的唯一實體
        /// </summary>
        public override DBTableSchemaBase TableSchema
        {
            get { return CST_SYS_LOADER_LOG.Singleton; }
        }
    
        #region Ctor()
        /// <summary>
        /// 建構一個空的 CST_SYS_LOADER_LOG_Row 物件.
        /// 此 Ctor 僅供 Cimes 內部 Generator 使用, 若要取得一 Row 實體, 請使用 Schema.NewRow()
        /// </summary>
        public CST_SYS_LOADER_LOG_Row() : base() {  }

        /// <summary>
        /// 以原生 DataRow 建構一個 CST_SYS_LOADER_LOG_Row 物件
        /// </summary>
        /// <param name="row">原生 DataRow</param>
        public CST_SYS_LOADER_LOG_Row(DataRow row) : base(row) {  }
        
        /// <summary>
        /// For Serializable Operation
        /// </summary>
        /// <param name="si">SerializationInfo</param>
        /// <param name="context">StreamingContext</param>
        protected CST_SYS_LOADER_LOG_Row(SerializationInfo si, StreamingContext context) : base(si, context) {  }
        #endregion

                    /// <summary>
    /// LOADER解析紀錄表SID 資料型態:NVARCHAR2(200) 是否允許Null:Y 
    /// </summary>
    public String SYS_LOADER_LOG { 
      get { return (this["SYS_LOADER_LOG"] is DBNull) ? string.Empty : (String) this["SYS_LOADER_LOG"]; } 
      set { this["SYS_LOADER_LOG"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 主要鍵值(序號/鍛造批號/小工單號) 資料型態:NVARCHAR2(200) 是否允許Null:Y 
    /// </summary>
    public String ITEM { 
      get { return (this["ITEM"] is DBNull) ? string.Empty : (String) this["ITEM"]; } 
      set { this["ITEM"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// LOADER名稱 資料型態:NVARCHAR2(200) 是否允許Null:Y 
    /// </summary>
    public String ITEM_TYPE { 
      get { return (this["ITEM_TYPE"] is DBNull) ? string.Empty : (String) this["ITEM_TYPE"]; } 
      set { this["ITEM_TYPE"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 解析的檔案名稱 資料型態:NVARCHAR2(200) 是否允許Null:Y 
    /// </summary>
    public String ITEM_FILE { 
      get { return (this["ITEM_FILE"] is DBNull) ? string.Empty : (String) this["ITEM_FILE"]; } 
      set { this["ITEM_FILE"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 檔案解析的結果(OK / NG) 資料型態:NVARCHAR2(200) 是否允許Null:Y 
    /// </summary>
    public String RESULT { 
      get { return (this["RESULT"] is DBNull) ? string.Empty : (String) this["RESULT"]; } 
      set { this["RESULT"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 解析成功紀錄SUCCESSFUL，失敗就紀錄ERROR原因 資料型態:NVARCHAR2(2000) 是否允許Null:Y 
    /// </summary>
    public String MESSAGE { 
      get { return (this["MESSAGE"] is DBNull) ? string.Empty : (String) this["MESSAGE"]; } 
      set { this["MESSAGE"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 紀錄LOG的時間 資料型態:NVARCHAR2(200) 是否允許Null:Y 
    /// </summary>
    public String RECTIME { 
      get { return (this["RECTIME"] is DBNull) ? string.Empty : (String) this["RECTIME"]; } 
      set { this["RECTIME"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 


        
        /// <summary>
        /// 取得該 Row 的深層複製實體
        /// </summary>              
        /// <returns>深層複製實體</returns>
        public new CST_SYS_LOADER_LOG_Row DeepCopy()
        {
            return (CST_SYS_LOADER_LOG_Row) base.DeepCopy();
        }
    }
}


