//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;
using System.Runtime.Serialization;
using System.Text;

using Ares.Cimes.IntelliService.DbTableSchema;

namespace Ares.Cimes.IntelliService.DbTableRow
{
    /// <summary>
    /// CST_WIP_RESERVE_CHECKIN_LOG_Row, 
    /// </summary>
    [Serializable]
    public class CST_WIP_RESERVE_CHECKIN_LOG_Row : DBTableRowBase
    {            
        /// <summary>
        /// 取得該 Row 是屬於 CST_WIP_RESERVE_CHECKIN_LOG Table, 傳回代表該 Table Schema 的唯一實體
        /// </summary>
        public override DBTableSchemaBase TableSchema
        {
            get { return CST_WIP_RESERVE_CHECKIN_LOG.Singleton; }
        }
    
        #region Ctor()
        /// <summary>
        /// 建構一個空的 CST_WIP_RESERVE_CHECKIN_LOG_Row 物件.
        /// 此 Ctor 僅供 Cimes 內部 Generator 使用, 若要取得一 Row 實體, 請使用 Schema.NewRow()
        /// </summary>
        public CST_WIP_RESERVE_CHECKIN_LOG_Row() : base() {  }

        /// <summary>
        /// 以原生 DataRow 建構一個 CST_WIP_RESERVE_CHECKIN_LOG_Row 物件
        /// </summary>
        /// <param name="row">原生 DataRow</param>
        public CST_WIP_RESERVE_CHECKIN_LOG_Row(DataRow row) : base(row) {  }
        
        /// <summary>
        /// For Serializable Operation
        /// </summary>
        /// <param name="si">SerializationInfo</param>
        /// <param name="context">StreamingContext</param>
        protected CST_WIP_RESERVE_CHECKIN_LOG_Row(SerializationInfo si, StreamingContext context) : base(si, context) {  }
        #endregion

                    /// <summary>
    /// 批號預約進站歷史紀錄系統編號 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String WIP_RESERVE_CHECKIN_LOG_SID { 
      get { return (this["WIP_RESERVE_CHECKIN_LOG_SID"] is DBNull) ? string.Empty : (String) this["WIP_RESERVE_CHECKIN_LOG_SID"]; } 
      set { this["WIP_RESERVE_CHECKIN_LOG_SID"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 批號預約進站系統編號 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String WIP_RESERVE_CHECKIN_INFO_SID { 
      get { return (this["WIP_RESERVE_CHECKIN_INFO_SID"] is DBNull) ? string.Empty : (String) this["WIP_RESERVE_CHECKIN_INFO_SID"]; } 
      set { this["WIP_RESERVE_CHECKIN_INFO_SID"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 批號 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String LOT { 
      get { return (this["LOT"] is DBNull) ? string.Empty : (String) this["LOT"]; } 
      set { this["LOT"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 工作站 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String OPERATION { 
      get { return (this["OPERATION"] is DBNull) ? string.Empty : (String) this["OPERATION"]; } 
      set { this["OPERATION"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 機台 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String EQUIPMENT { 
      get { return (this["EQUIPMENT"] is DBNull) ? string.Empty : (String) this["EQUIPMENT"]; } 
      set { this["EQUIPMENT"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 規則名稱 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String RULENAME { 
      get { return (this["RULENAME"] is DBNull) ? string.Empty : (String) this["RULENAME"]; } 
      set { this["RULENAME"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 預約進站時間 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String INTIME { 
      get { return (this["INTIME"] is DBNull) ? string.Empty : (String) this["INTIME"]; } 
      set { this["INTIME"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 實際出站時間 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String OUTTIME { 
      get { return (this["OUTTIME"] is DBNull) ? string.Empty : (String) this["OUTTIME"]; } 
      set { this["OUTTIME"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 當次作業的繫結ID 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String LINKSID { 
      get { return (this["LINKSID"] is DBNull) ? string.Empty : (String) this["LINKSID"]; } 
      set { this["LINKSID"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 


        
        /// <summary>
        /// 取得該 Row 的深層複製實體
        /// </summary>              
        /// <returns>深層複製實體</returns>
        public new CST_WIP_RESERVE_CHECKIN_LOG_Row DeepCopy()
        {
            return (CST_WIP_RESERVE_CHECKIN_LOG_Row) base.DeepCopy();
        }
    }
}


