//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;
using System.Runtime.Serialization;
using System.Text;

using Ares.Cimes.IntelliService.DbTableSchema;

namespace Ares.Cimes.IntelliService.DbTableRow
{
    /// <summary>
    /// CST_WPC_WO_ROUTE_Row, 
    /// </summary>
    [Serializable]
    public class CST_WPC_WO_ROUTE_Row : DBTableRowBase
    {            
        /// <summary>
        /// 取得該 Row 是屬於 CST_WPC_WO_ROUTE Table, 傳回代表該 Table Schema 的唯一實體
        /// </summary>
        public override DBTableSchemaBase TableSchema
        {
            get { return CST_WPC_WO_ROUTE.Singleton; }
        }
    
        #region Ctor()
        /// <summary>
        /// 建構一個空的 CST_WPC_WO_ROUTE_Row 物件.
        /// 此 Ctor 僅供 Cimes 內部 Generator 使用, 若要取得一 Row 實體, 請使用 Schema.NewRow()
        /// </summary>
        public CST_WPC_WO_ROUTE_Row() : base() {  }

        /// <summary>
        /// 以原生 DataRow 建構一個 CST_WPC_WO_ROUTE_Row 物件
        /// </summary>
        /// <param name="row">原生 DataRow</param>
        public CST_WPC_WO_ROUTE_Row(DataRow row) : base(row) {  }
        
        /// <summary>
        /// For Serializable Operation
        /// </summary>
        /// <param name="si">SerializationInfo</param>
        /// <param name="context">StreamingContext</param>
        protected CST_WPC_WO_ROUTE_Row(SerializationInfo si, StreamingContext context) : base(si, context) {  }
        #endregion

                    /// <summary>
    /// 表SID 資料型態:NVARCHAR2(40) 是否允許Null:Y 
    /// </summary>
    public String WPC_WO_ROUTE_SID { 
      get { return (this["WPC_WO_ROUTE_SID"] is DBNull) ? string.Empty : (String) this["WPC_WO_ROUTE_SID"]; } 
      set { this["WPC_WO_ROUTE_SID"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 工單號碼 資料型態:NVARCHAR2(10) 是否允許Null:Y 
    /// </summary>
    public String AUFNR { 
      get { return (this["AUFNR"] is DBNull) ? string.Empty : (String) this["AUFNR"]; } 
      set { this["AUFNR"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 途程代碼 資料型態:NVARCHAR2(40) 是否允許Null:Y 
    /// </summary>
    public String PLNNR { 
      get { return (this["PLNNR"] is DBNull) ? string.Empty : (String) this["PLNNR"]; } 
      set { this["PLNNR"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 作業號碼 資料型態:NVARCHAR2(40) 是否允許Null:Y 
    /// </summary>
    public String VORNR { 
      get { return (this["VORNR"] is DBNull) ? string.Empty : (String) this["VORNR"]; } 
      set { this["VORNR"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 工作中心 資料型態:NVARCHAR2(40) 是否允許Null:Y 
    /// </summary>
    public String ARBPL { 
      get { return (this["ARBPL"] is DBNull) ? string.Empty : (String) this["ARBPL"]; } 
      set { this["ARBPL"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 作業短文 資料型態:NVARCHAR2(40) 是否允許Null:Y 
    /// </summary>
    public String LTXA1 { 
      get { return (this["LTXA1"] is DBNull) ? string.Empty : (String) this["LTXA1"]; } 
      set { this["LTXA1"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 基礎數量 資料型態:NVARCHAR2(40) 是否允許Null:Y 
    /// </summary>
    public String BMSCH { 
      get { return (this["BMSCH"] is DBNull) ? string.Empty : (String) this["BMSCH"]; } 
      set { this["BMSCH"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 單位 資料型態:NVARCHAR2(40) 是否允許Null:Y 
    /// </summary>
    public String MEINH { 
      get { return (this["MEINH"] is DBNull) ? string.Empty : (String) this["MEINH"]; } 
      set { this["MEINH"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 長文 資料型態:NVARCHAR2(40) 是否允許Null:Y 
    /// </summary>
    public String LTEXT { 
      get { return (this["LTEXT"] is DBNull) ? string.Empty : (String) this["LTEXT"]; } 
      set { this["LTEXT"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 資料抓取時間 資料型態:NVARCHAR2(20) 是否允許Null:Y 
    /// </summary>
    public String UPDATETIME { 
      get { return (this["UPDATETIME"] is DBNull) ? string.Empty : (String) this["UPDATETIME"]; } 
      set { this["UPDATETIME"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 


        
        /// <summary>
        /// 取得該 Row 的深層複製實體
        /// </summary>              
        /// <returns>深層複製實體</returns>
        public new CST_WPC_WO_ROUTE_Row DeepCopy()
        {
            return (CST_WPC_WO_ROUTE_Row) base.DeepCopy();
        }
    }
}


