//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;
using System.Runtime.Serialization;
using System.Text;

using Ares.Cimes.IntelliService.DbTableSchema;

namespace Ares.Cimes.IntelliService.DbTableRow
{
    /// <summary>
    /// CST_WMS_MAST_BAK_Row, 
    /// </summary>
    [Serializable]
    public class CST_WMS_MAST_BAK_Row : DBTableRowBase
    {            
        /// <summary>
        /// 取得該 Row 是屬於 CST_WMS_MAST_BAK Table, 傳回代表該 Table Schema 的唯一實體
        /// </summary>
        public override DBTableSchemaBase TableSchema
        {
            get { return CST_WMS_MAST_BAK.Singleton; }
        }
    
        #region Ctor()
        /// <summary>
        /// 建構一個空的 CST_WMS_MAST_BAK_Row 物件.
        /// 此 Ctor 僅供 Cimes 內部 Generator 使用, 若要取得一 Row 實體, 請使用 Schema.NewRow()
        /// </summary>
        public CST_WMS_MAST_BAK_Row() : base() {  }

        /// <summary>
        /// 以原生 DataRow 建構一個 CST_WMS_MAST_BAK_Row 物件
        /// </summary>
        /// <param name="row">原生 DataRow</param>
        public CST_WMS_MAST_BAK_Row(DataRow row) : base(row) {  }
        
        /// <summary>
        /// For Serializable Operation
        /// </summary>
        /// <param name="si">SerializationInfo</param>
        /// <param name="context">StreamingContext</param>
        protected CST_WMS_MAST_BAK_Row(SerializationInfo si, StreamingContext context) : base(si, context) {  }
        #endregion

                    /// <summary>
    /// 入庫主檔領用紀錄系統編號 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String WMS_MAST_BAK_SID { 
      get { return (this["WMS_MAST_BAK_SID"] is DBNull) ? string.Empty : (String) this["WMS_MAST_BAK_SID"]; } 
      set { this["WMS_MAST_BAK_SID"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 入庫主檔系統編號 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String WMS_MAST_SID { 
      get { return (this["WMS_MAST_SID"] is DBNull) ? string.Empty : (String) this["WMS_MAST_SID"]; } 
      set { this["WMS_MAST_SID"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 入庫批號 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String LOT { 
      get { return (this["LOT"] is DBNull) ? string.Empty : (String) this["LOT"]; } 
      set { this["LOT"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 入庫料號 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String DEVICE { 
      get { return (this["DEVICE"] is DBNull) ? string.Empty : (String) this["DEVICE"]; } 
      set { this["DEVICE"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 領用批號 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String RECEIVELOT { 
      get { return (this["RECEIVELOT"] is DBNull) ? string.Empty : (String) this["RECEIVELOT"]; } 
      set { this["RECEIVELOT"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 主檔與明細的關聯編號 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String LIKSID { 
      get { return (this["LIKSID"] is DBNull) ? string.Empty : (String) this["LIKSID"]; } 
      set { this["LIKSID"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 領用時間 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String UPDATETIME { 
      get { return (this["UPDATETIME"] is DBNull) ? string.Empty : (String) this["UPDATETIME"]; } 
      set { this["UPDATETIME"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 領用人 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String USERID { 
      get { return (this["USERID"] is DBNull) ? string.Empty : (String) this["USERID"]; } 
      set { this["USERID"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 


        
        /// <summary>
        /// 取得該 Row 的深層複製實體
        /// </summary>              
        /// <returns>深層複製實體</returns>
        public new CST_WMS_MAST_BAK_Row DeepCopy()
        {
            return (CST_WMS_MAST_BAK_Row) base.DeepCopy();
        }
    }
}


