//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;
using System.Runtime.Serialization;
using System.Text;

using Ares.Cimes.IntelliService.DbTableSchema;

namespace Ares.Cimes.IntelliService.DbTableRow
{
    /// <summary>
    /// CST_WPC_WO_BOM_Row, 工單BOM資料
    /// </summary>
    [Serializable]
    public class CST_WPC_WO_BOM_Row : DBTableRowBase
    {            
        /// <summary>
        /// 取得該 Row 是屬於 CST_WPC_WO_BOM Table, 傳回代表該 Table Schema 的唯一實體
        /// </summary>
        public override DBTableSchemaBase TableSchema
        {
            get { return CST_WPC_WO_BOM.Singleton; }
        }
    
        #region Ctor()
        /// <summary>
        /// 建構一個空的 CST_WPC_WO_BOM_Row 物件.
        /// 此 Ctor 僅供 Cimes 內部 Generator 使用, 若要取得一 Row 實體, 請使用 Schema.NewRow()
        /// </summary>
        public CST_WPC_WO_BOM_Row() : base() {  }

        /// <summary>
        /// 以原生 DataRow 建構一個 CST_WPC_WO_BOM_Row 物件
        /// </summary>
        /// <param name="row">原生 DataRow</param>
        public CST_WPC_WO_BOM_Row(DataRow row) : base(row) {  }
        
        /// <summary>
        /// For Serializable Operation
        /// </summary>
        /// <param name="si">SerializationInfo</param>
        /// <param name="context">StreamingContext</param>
        protected CST_WPC_WO_BOM_Row(SerializationInfo si, StreamingContext context) : base(si, context) {  }
        #endregion

                    /// <summary>
    /// 表SID 資料型態:NVARCHAR2(40) 是否允許Null:Y 
    /// </summary>
    public String WPC_WO_BOM_SID { 
      get { return (this["WPC_WO_BOM_SID"] is DBNull) ? string.Empty : (String) this["WPC_WO_BOM_SID"]; } 
      set { this["WPC_WO_BOM_SID"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 工單號碼 資料型態:NVARCHAR2(10) 是否允許Null:Y 
    /// </summary>
    public String AUFNR { 
      get { return (this["AUFNR"] is DBNull) ? string.Empty : (String) this["AUFNR"]; } 
      set { this["AUFNR"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 項目 資料型態:NVARCHAR2(4) 是否允許Null:Y 
    /// </summary>
    public String POSNR { 
      get { return (this["POSNR"] is DBNull) ? string.Empty : (String) this["POSNR"]; } 
      set { this["POSNR"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 元件 資料型態:NVARCHAR2(18) 是否允許Null:Y 
    /// </summary>
    public String MATNR { 
      get { return (this["MATNR"] is DBNull) ? string.Empty : (String) this["MATNR"]; } 
      set { this["MATNR"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 說明 資料型態:NVARCHAR2(40) 是否允許Null:Y 
    /// </summary>
    public String MATXT { 
      get { return (this["MATXT"] is DBNull) ? string.Empty : (String) this["MATXT"]; } 
      set { this["MATXT"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 需求數量 資料型態:NUMBER(13) 是否允許Null:Y 
    /// </summary>
    public Decimal MENGE { 
      get { return (this["MENGE"] is DBNull) ? 0 : decimal.Parse(this["MENGE"].ToString()).FormatDecimal(); } 
      set { this["MENGE"] = value; } 
    } 

    /// <summary>
    /// 計量單位 資料型態:NVARCHAR2(3) 是否允許Null:Y 
    /// </summary>
    public String EINHEIT { 
      get { return (this["EINHEIT"] is DBNull) ? string.Empty : (String) this["EINHEIT"]; } 
      set { this["EINHEIT"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 作業 資料型態:NVARCHAR2(4) 是否允許Null:Y 
    /// </summary>
    public String VORNR { 
      get { return (this["VORNR"] is DBNull) ? string.Empty : (String) this["VORNR"]; } 
      set { this["VORNR"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 工廠 資料型態:NVARCHAR2(4) 是否允許Null:Y 
    /// </summary>
    public String WERKS { 
      get { return (this["WERKS"] is DBNull) ? string.Empty : (String) this["WERKS"]; } 
      set { this["WERKS"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 儲位 資料型態:NVARCHAR2(4) 是否允許Null:Y 
    /// </summary>
    public String LGORT { 
      get { return (this["LGORT"] is DBNull) ? string.Empty : (String) this["LGORT"]; } 
      set { this["LGORT"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 批次 資料型態:NVARCHAR2(13) 是否允許Null:Y 
    /// </summary>
    public String CHARG { 
      get { return (this["CHARG"] is DBNull) ? string.Empty : (String) this["CHARG"]; } 
      set { this["CHARG"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 已刪除 資料型態:NVARCHAR2(1) 是否允許Null:Y 
    /// </summary>
    public String XLOEK { 
      get { return (this["XLOEK"] is DBNull) ? string.Empty : (String) this["XLOEK"]; } 
      set { this["XLOEK"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 需求日期 資料型態:NVARCHAR2(8) 是否允許Null:Y 
    /// </summary>
    public String BDTER { 
      get { return (this["BDTER"] is DBNull) ? string.Empty : (String) this["BDTER"]; } 
      set { this["BDTER"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 更新時間 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String UPDATETIME { 
      get { return (this["UPDATETIME"] is DBNull) ? string.Empty : (String) this["UPDATETIME"]; } 
      set { this["UPDATETIME"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    }

        /// <summary>
        /// 區分料別，1：主料，2：華司料 資料型態:NVARCHAR2(100) 是否允許Null:Y 
        /// </summary>
        public String SORTF
        {
            get { return (this["SORTF"] is DBNull) ? string.Empty : (String)this["SORTF"]; }
            set { this["SORTF"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object)value; }
        }



        /// <summary>
        /// 取得該 Row 的深層複製實體
        /// </summary>              
        /// <returns>深層複製實體</returns>
        public new CST_WPC_WO_BOM_Row DeepCopy()
        {
            return (CST_WPC_WO_BOM_Row) base.DeepCopy();
        }
    }
}


