//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;
using System.Runtime.Serialization;
using System.Text;

using Ares.Cimes.IntelliService.DbTableSchema;

namespace Ares.Cimes.IntelliService.DbTableRow
{
    /// <summary>
    /// CST_CPF_ELEC_HOTSTOVE_Row, 三向鍛電熱爐溫度資料表
    /// </summary>
    [Serializable]
    public class CST_CPF_ELEC_HOTSTOVE_Row : DBTableRowBase
    {            
        /// <summary>
        /// 取得該 Row 是屬於 CST_CPF_ELEC_HOTSTOVE Table, 傳回代表該 Table Schema 的唯一實體
        /// </summary>
        public override DBTableSchemaBase TableSchema
        {
            get { return CST_CPF_ELEC_HOTSTOVE.Singleton; }
        }
    
        #region Ctor()
        /// <summary>
        /// 建構一個空的 CST_CPF_ELEC_HOTSTOVE_Row 物件.
        /// 此 Ctor 僅供 Cimes 內部 Generator 使用, 若要取得一 Row 實體, 請使用 Schema.NewRow()
        /// </summary>
        public CST_CPF_ELEC_HOTSTOVE_Row() : base() {  }

        /// <summary>
        /// 以原生 DataRow 建構一個 CST_CPF_ELEC_HOTSTOVE_Row 物件
        /// </summary>
        /// <param name="row">原生 DataRow</param>
        public CST_CPF_ELEC_HOTSTOVE_Row(DataRow row) : base(row) {  }
        
        /// <summary>
        /// For Serializable Operation
        /// </summary>
        /// <param name="si">SerializationInfo</param>
        /// <param name="context">StreamingContext</param>
        protected CST_CPF_ELEC_HOTSTOVE_Row(SerializationInfo si, StreamingContext context) : base(si, context) {  }
        #endregion

                    /// <summary>
    /// SID 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String CPF_ELEC_HOTSTOVE_SID { 
      get { return (this["CPF_ELEC_HOTSTOVE_SID"] is DBNull) ? string.Empty : (String) this["CPF_ELEC_HOTSTOVE_SID"]; } 
      set { this["CPF_ELEC_HOTSTOVE_SID"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 線別 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String LINE { 
      get { return (this["LINE"] is DBNull) ? string.Empty : (String) this["LINE"]; } 
      set { this["LINE"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 三向鍛的第幾階段(A:擠型;B:粗鍛;C:細鍛) 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String STEP { 
      get { return (this["STEP"] is DBNull) ? string.Empty : (String) this["STEP"]; } 
      set { this["STEP"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 溫度計的第幾個位置 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String LOCATION { 
      get { return (this["LOCATION"] is DBNull) ? string.Empty : (String) this["LOCATION"]; } 
      set { this["LOCATION"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 溫度 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String TEMP { 
      get { return (this["TEMP"] is DBNull) ? string.Empty : (String) this["TEMP"]; } 
      set { this["TEMP"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 使用者 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String USERID { 
      get { return (this["USERID"] is DBNull) ? string.Empty : (String) this["USERID"]; } 
      set { this["USERID"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 更新時間 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String UPDATETIME { 
      get { return (this["UPDATETIME"] is DBNull) ? string.Empty : (String) this["UPDATETIME"]; } 
      set { this["UPDATETIME"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 


        
        /// <summary>
        /// 取得該 Row 的深層複製實體
        /// </summary>              
        /// <returns>深層複製實體</returns>
        public new CST_CPF_ELEC_HOTSTOVE_Row DeepCopy()
        {
            return (CST_CPF_ELEC_HOTSTOVE_Row) base.DeepCopy();
        }
    }
}


