//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;
using System.Runtime.Serialization;
using System.Text;

using Ares.Cimes.IntelliService.DbTableSchema;

namespace Ares.Cimes.IntelliService.DbTableRow
{
    /// <summary>
    /// CST_WPC_WO_LOT_Row, 
    /// </summary>
    [Serializable]
    public class CST_WPC_WO_LOT_Row : DBTableRowBase
    {            
        /// <summary>
        /// 取得該 Row 是屬於 CST_WPC_WO_LOT Table, 傳回代表該 Table Schema 的唯一實體
        /// </summary>
        public override DBTableSchemaBase TableSchema
        {
            get { return CST_WPC_WO_LOT.Singleton; }
        }
    
        #region Ctor()
        /// <summary>
        /// 建構一個空的 CST_WPC_WO_LOT_Row 物件.
        /// 此 Ctor 僅供 Cimes 內部 Generator 使用, 若要取得一 Row 實體, 請使用 Schema.NewRow()
        /// </summary>
        public CST_WPC_WO_LOT_Row() : base() {  }

        /// <summary>
        /// 以原生 DataRow 建構一個 CST_WPC_WO_LOT_Row 物件
        /// </summary>
        /// <param name="row">原生 DataRow</param>
        public CST_WPC_WO_LOT_Row(DataRow row) : base(row) {  }
        
        /// <summary>
        /// For Serializable Operation
        /// </summary>
        /// <param name="si">SerializationInfo</param>
        /// <param name="context">StreamingContext</param>
        protected CST_WPC_WO_LOT_Row(SerializationInfo si, StreamingContext context) : base(si, context) {  }
        #endregion

                    /// <summary>
    /// 工單批號明細系統編號 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String WPC_WO_LOT_SID { 
      get { return (this["WPC_WO_LOT_SID"] is DBNull) ? string.Empty : (String) this["WPC_WO_LOT_SID"]; } 
      set { this["WPC_WO_LOT_SID"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 工單 資料型態:NVARCHAR2(100) 是否允許Null:N 
    /// </summary>
    public String WO { 
      get { return (this["WO"] is DBNull) ? string.Empty : (String) this["WO"]; } 
      set { this["WO"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 工單序號 資料型態:NUMBER(38) 是否允許Null:N 
    /// </summary>
    public Decimal WOSEQUENCE { 
      get { return (this["WOSEQUENCE"] is DBNull) ? 0 : decimal.Parse(this["WOSEQUENCE"].ToString()).FormatDecimal(); } 
      set { this["WOSEQUENCE"] = value; } 
    } 

    /// <summary>
    /// 工單批 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String WOLOT { 
      get { return (this["WOLOT"] is DBNull) ? string.Empty : (String) this["WOLOT"]; } 
      set { this["WOLOT"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 入庫批 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String INVLOT { 
      get { return (this["INVLOT"] is DBNull) ? string.Empty : (String) this["INVLOT"]; } 
      set { this["INVLOT"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 物料批 資料型態:NVARCHAR2(100) 是否允許Null:Y 
    /// </summary>
    public String MATERIALLOT { 
      get { return (this["MATERIALLOT"] is DBNull) ? string.Empty : (String) this["MATERIALLOT"]; } 
      set { this["MATERIALLOT"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    } 

    /// <summary>
    /// 發料數量 資料型態:NUMBER(13) 是否允許Null:Y 
    /// </summary>
    public Decimal QUANTITY { 
      get { return (this["QUANTITY"] is DBNull) ? 0 : decimal.Parse(this["QUANTITY"].ToString()).FormatDecimal(); } 
      set { this["QUANTITY"] = value; } 
    }

    /// <summary>
    /// 領料狀態 Y:已領料、N:未領料	 資料型態:NVARCHAR2(100) 是否允許Null:N 
    /// </summary>
    public String CREATEFLAG { 
      get { return (this["CREATEFLAG"] is DBNull) ? string.Empty : (String) this["CREATEFLAG"]; } 
      set { this["CREATEFLAG"] = string.IsNullOrEmpty(value) ? DBNull.Value : (object) value; } 
    }


        
        /// <summary>
        /// 取得該 Row 的深層複製實體
        /// </summary>              
        /// <returns>深層複製實體</returns>
        public new CST_WPC_WO_LOT_Row DeepCopy()
        {
            return (CST_WPC_WO_LOT_Row) base.DeepCopy();
        }
    }
}


