//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;


using Ares.Cimes.IntelliService.DbTableRow;
using Ares.Cimes.IntelliService.DbTableSchema;

namespace Ares.Cimes.IntelliService.Info
{
    /// <summary>
    /// 設備上下工資料 (Mapping CST_EQP_WORKTIME Table)
    /// </summary>
    public partial class CSTEquipmentWorktimeInfo 
    {
        public static CSTEquipmentWorktimeInfo GetEquipmentWorktimeByEquipmentAndLot(string equipment, string lot)
        {
            return InfoCenter.GetBySQL<CSTEquipmentWorktimeInfo>("SELECT * FROM CST_EQP_WORKTIME WHERE EQUIPMENT = #[STRING] AND LOT = #[STRING] AND ENDTIME IS NULL", equipment, lot);
        }

        public static List<CSTEquipmentWorktimeInfo> GetEquipmentWorktimeByEquipment(string equipment)
        {
            return InfoCenter.GetList<CSTEquipmentWorktimeInfo>("SELECT * FROM CST_EQP_WORKTIME WHERE EQUIPMENT = #[STRING] AND ENDTIME IS NULL", equipment);
        }

        /************************以上FUNCTION, INDEX 已確認，新增FUNCTION請往下新增**************************/

        /// <summary>
        /// 調機完成抓機時所以批號要是空白
        /// </summary>
        /// <param name="equipment"></param>
        /// <param name="wo"></param>
        /// <returns></returns>
        public static CSTEquipmentWorktimeInfo GetEquipmentWorktimeByEquipmentAndWO(string equipment, string wo)
        {
            return InfoCenter.GetBySQL<CSTEquipmentWorktimeInfo>("SELECT * FROM CST_EQP_WORKTIME WHERE EQUIPMENT = #[STRING] AND WO = #[STRING] AND ENDTIME IS NULL AND LOT IS NULL", equipment, wo);
        }

    }
}

