//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;


using Ares.Cimes.IntelliService.DbTableRow;
using Ares.Cimes.IntelliService.DbTableSchema;

namespace Ares.Cimes.IntelliService.Info
{

    public partial class CSTPrcLineInfo 
    {
        public static CSTPrcLineInfo GetLineInfoByLine(string line)
        {
            return InfoCenter.GetBySQL<CSTPrcLineInfo>("SELECT * FROM CST_PRC_LINE WHERE LINE = #[STRING]", line);
        }

        public static List<CSTPrcLineInfo> GetAllLine()
        {
            return InfoCenter.GetList<CSTPrcLineInfo>("SELECT * FROM CST_PRC_LINE");
        }

        /************************以上FUNCTION, INDEX 已確認，新增FUNCTION請往下新增**************************/

    }
}

