//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;


using Ares.Cimes.IntelliService.DbTableRow;
using Ares.Cimes.IntelliService.DbTableSchema;

namespace Ares.Cimes.IntelliService.Info
{

    public partial class CSTPRCOperationMappingDataInfo
    {
        public static CSTPRCOperationMappingDataInfo GetOperationMappingDataByMESOperation(string operation)
        {
            return InfoCenter.GetBySQL<CSTPRCOperationMappingDataInfo>("SELECT * FROM CST_PRC_OPER_MAPPING_DATA WHERE MESOPER =#[STRING]", operation);
        }
    }
}

