//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，這個檔案將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Data;


using Ares.Cimes.IntelliService.DbTableRow;
using Ares.Cimes.IntelliService.DbTableSchema;

namespace Ares.Cimes.IntelliService.Info
{
    public partial class CSTUserWorkTimeInfo
    {
        public static CSTUserWorkTimeInfo GetUserWorkTimeByWOAndUserIDAndWorkPlace(string lot, string workUserID, string userWorkPlace)
        {
            if (userWorkPlace.IsNullOrTrimEmpty())
            {
                return InfoCenter.GetBySQL<CSTUserWorkTimeInfo>("SELECT * FROM CST_USR_WORKTIME WHERE LOT = #[STRING] AND WORKUSERID = #[STRING] AND ENDTIME IS NULL", lot, workUserID);
            }
            else
            {
                return InfoCenter.GetBySQL<CSTUserWorkTimeInfo>("SELECT * FROM CST_USR_WORKTIME WHERE LOT = #[STRING] AND WORKUSERID = #[STRING] AND USR_WORKPALCE = #[STRING] AND ENDTIME IS NULL", lot, workUserID, userWorkPlace);
            }
        }

        /// <summary>
        /// 出站呼叫
        /// </summary>
        /// <param name="equipment"></param>
        /// <param name="workUserID"></param>
        /// <param name="lot"></param>
        /// <returns></returns>
        public static CSTUserWorkTimeInfo GetUserWorkTimeListByEquipmentAndWorkUserIDAndLot(string equipment, string workUserID, string lot)
        {
            return InfoCenter.GetBySQL<CSTUserWorkTimeInfo>("SELECT * FROM CST_USR_WORKTIME WHERE LINE =#[STRING] AND WORKUSERID = #[STRING] AND LOT = #[STRING] AND ENDTIME IS NULL", equipment, workUserID, lot);
        }

        public static CSTUserWorkTimeInfo GetUserWorkTimeByEquipmentAndWorkplaceAndUser(string wo, string equipment, string workplace, string workuser)
        {
            return InfoCenter.GetBySQL<CSTUserWorkTimeInfo>("SELECT * FROM CST_USR_WORKTIME WHERE WO = #[STRING] AND LINE =#[STRING] AND USR_WORKPALCE = #[STRING] AND WORKUSERID = #[STRING] AND ENDTIME IS NULL", wo, equipment, workplace, workuser);
        }

        public static List<CSTUserWorkTimeInfo> GetUserWorkTimeListByEquipmentAndStation(string equipment, string station)
        {
            return InfoCenter.GetList<CSTUserWorkTimeInfo>("SELECT * FROM CST_USR_WORKTIME WHERE LINE =#[STRING] AND USR_WORKPALCE =#[STRING] AND ENDTIME IS NULL", equipment, station);
        }

        public static CSTUserWorkTimeInfo GetUserWorkTimeByWOAndEquipmentAndUser(string wo, string equipment, string workuser)
        {
            return InfoCenter.GetBySQL<CSTUserWorkTimeInfo>("SELECT * FROM CST_USR_WORKTIME WHERE WO = #[STRING] AND LINE =#[STRING] AND WORKUSERID = #[STRING] AND ENDTIME IS NULL", wo, equipment, workuser);
        }

        public static List<CSTUserWorkTimeInfo> GetUserWorkTimeListByEquipment(string equipment)
        {
            return InfoCenter.GetList<CSTUserWorkTimeInfo>("SELECT * FROM CST_USR_WORKTIME WHERE LINE =#[STRING] AND ENDTIME IS NULL", equipment);
        }

        public static List<CSTUserWorkTimeInfo> GetUserWorkTimeListByWorkUser(string workuserid)
        {
            return InfoCenter.GetList<CSTUserWorkTimeInfo>("SELECT * FROM CST_USR_WORKTIME WHERE WORKUSERID =#[STRING] AND ENDTIME IS NULL AND LOT IS NOT NULL", workuserid);
        }

        /************************以上FUNCTION, INDEX 已確認，新增FUNCTION請往下新增**************************/

        public static CSTUserWorkTimeInfo GetUserWorkTimeByLotAndUser(string lot, string workuser)
        {
            return InfoCenter.GetBySQL<CSTUserWorkTimeInfo>("SELECT * FROM CST_USR_WORKTIME WHERE LOT = #[STRING] AND WORKUSERID = #[STRING] AND ENDTIME IS NULL", lot, workuser);
        }

        public static List<CSTUserWorkTimeInfo> GetUserWorkTimeByLot(string lot)
        {
            return InfoCenter.GetList<CSTUserWorkTimeInfo>("SELECT * FROM CST_USR_WORKTIME WHERE LOT = #[STRING] AND ENDTIME IS NULL", lot);
        }

        /// <summary>
        /// 下工調機工時使用
        /// </summary>
        /// <param name="lot"></param>
        /// <returns></returns>
        public static List<CSTUserWorkTimeInfo> GetSetupUnFinishUserWorkTime(string userid)
        {
            return InfoCenter.GetList<CSTUserWorkTimeInfo>("SELECT * FROM CST_USR_WORKTIME WHERE WORKUSERID = #[STRING] AND ENDTIME IS NULL AND LOT IS NULL AND OPERATION IS NULL", userid);
        }

    }
}

